import {it,describe} from 'vitest';
import assert from 'node:assert/strict';
import {prepareFieldingExecution} from './FieldingExecution';
import {fixture,change,value} from './FieldingFixtures.test-support';
import {createRatedThrowLaunch} from '../../../sim/fielding/ThrowLaunch';
import {advanceBallState,DEFAULT_BALL_FLIGHT_PARAMETERS} from '../../../sim/ball/BallFlight';
import {DeterministicRng} from '../../../rng/DeterministicRng';
import type {FieldingExecutionRequest,ThrowPhysicalPlan} from './FieldingTypes';
const plan=(r:FieldingExecutionRequest):ThrowPhysicalPlan=>{const p=value(prepareFieldingExecution(r));assert.equal(p.status,'READY');assert.equal(p.plan?.kind,'THROW');return p.plan as ThrowPhysicalPlan;};
describe('emotion reaches an existing physical throw launch',()=>{
 it('neutral matches the existing launch exactly',()=>{const r=fixture(),s=r.source;if(s.kind!=='THROW')assert.fail();const p=plan(r);assert.deepEqual(p.launch,createRatedThrowLaunch({releaseTick:160,origin:s.origin,intendedTarget:s.target,armStrength:s.armStrength,throwingAccuracy:s.throwingAccuracy,rng:new DeterministicRng(s.randomSeed),calibration:s.profiles[0].calibration}));});
 it('delayed intent delays release without changing velocity or accuracy',()=>{const n=plan(fixture()),p=plan(fixture('THROW','SUPERIORITY',{throwIntentShiftTicks:15}));assert.equal(p.launch.releaseTick,n.launch.releaseTick+15);assert.deepEqual(p.launch.initialVelocity,n.launch.initialVelocity);assert.deepEqual(p.launch.targetError,n.launch.targetError);});
 it('the same physical flight has a different position at a common clock tick',()=>{const n=plan(fixture()),p=plan(fixture('THROW','SUPERIORITY',{throwIntentShiftTicks:15}));const at=(x:ThrowPhysicalPlan)=>advanceBallState({tick:x.launch.releaseTick,position:x.launch.origin,velocity:x.launch.initialVelocity,spin:{x:0,y:0,z:0}},300-x.launch.releaseTick,{...DEFAULT_BALL_FLIGHT_PARAMETERS,ticksPerSecond:1000,integrationStepTicks:1});assert.ok(at(n).position.x>at(p).position.x);});
 it('does not double charge transfer that completed before intent',()=>{const p=plan(fixture());assert.equal(p.transfer.throwReadyTick,120);assert.equal(p.motorStartTick,140);assert.equal(p.launch.releaseTick,160);});
 it('early intention respects the physical earliest commitment bound',()=>{const r=change(fixture('THROW','IMPATIENCE',{throwIntentShiftTicks:-100}),d=>{d.source.securedPossessionTick=100;});const p=plan(r);assert.equal(p.commitmentTick,125);assert.equal(p.motorStartTick,125);assert.equal(p.launch.releaseTick,145);});
 it('waits for a genuinely longer transfer without boosting transfer ability',()=>{const r=change(fixture(),d=>{d.source.transfer.minimumTransferDelayTicks=60;d.source.transfer.maximumTransferDelayTicks=100;});const p=plan(r);assert.equal(p.transfer.throwReadyTick,180);assert.equal(p.motorStartTick,180);assert.equal(p.launch.releaseTick,200);});
 it('aggression selects an existing stronger profile, not an arm bonus',()=>{const n=plan(fixture()),r=fixture('THROW','ANGER',{throwAggressionDelta:0.5}),p=plan(r);assert.equal(p.profileId,'strong');assert.ok(p.launch.releaseSpeedMps>n.launch.releaseSpeedMps);assert.equal((r.source as {armStrength:number}).armStrength,0.75);});
 it('an exactly met profile threshold selects that profile',()=>{const r=fixture('THROW','ANGER',{throwAggressionDelta:0.3});assert.equal(plan(r).profileId,'strong');});
 it('fear selects the normal lower-effort repertoire entry',()=>{assert.equal(plan(fixture('THROW','FEAR',{throwAggressionDelta:-0.4})).profileId,'controlled');});
 it('no possession produces no launch',()=>{const r=change(fixture(),d=>d.source.holderId=null),p=value(prepareFieldingExecution(r));assert.equal(p.status,'NO_CONTROL');assert.equal(p.plan,null);});
 it('another holder cannot be treated as this thrower',()=>{const r=change(fixture(),d=>d.source.holderId='other'),p=value(prepareFieldingExecution(r));assert.equal(p.status,'NO_CONTROL');assert.equal(p.plan,null);});
 it('moving throws require a body adapter rather than freezing a moving origin',()=>{const r=change(fixture(),d=>d.source.holderVelocity.x=1);assert.equal(prepareFieldingExecution(r).ok,false);});
 it('a release beyond source validity is a missed window, not clamped backward',()=>{const r=change(fixture(),d=>d.source.validUntilTick=150),p=value(prepareFieldingExecution(r));assert.equal(p.status,'MISSED_WINDOW');assert.equal(p.plan,null);});
 it('rejects a profile exceeding physical speed ceiling',()=>{const r=change(fixture(),d=>d.source.profiles[1].calibration.maximumReleaseSpeedMps=41);assert.equal(prepareFieldingExecution(r).ok,false);});
 it('rejects identical receiver and thrower',()=>{const r=change(fixture(),d=>d.source.receiverId=d.currentFrame.scope.playerId);assert.equal(prepareFieldingExecution(r).ok,false);});
 it('rejects missing zero-aggression coverage',()=>{const r=change(fixture(),d=>d.source.profiles[0].minimumAggression=0.1);assert.equal(prepareFieldingExecution(r).ok,false);});
 it('rejects duplicate thresholds and profile IDs',()=>{for(const key of ['profileId','minimumAggression']){const r=change(fixture(),d=>d.source.profiles[1][key]=d.source.profiles[0][key]);assert.equal(prepareFieldingExecution(r).ok,false);}});
 it('rejects invalid random seeds instead of silently truncating',()=>{for(const seed of [-1,1.5,2**32,NaN]){const r=change(fixture(),d=>d.source.randomSeed=seed);assert.equal(prepareFieldingExecution(r).ok,false);}});
 it('rejects numerical overflow in motor timing',()=>{const r=change(fixture(),d=>d.source.profiles[0].motorDurationTicks=Number.MAX_SAFE_INTEGER);assert.equal(prepareFieldingExecution(r).ok,false);});
 it('repeated preparation uses the same isolated random stream',()=>{const r=fixture();assert.deepEqual(plan(r),plan(r));});
});
