import {it,describe} from 'vitest';
import assert from 'node:assert/strict';
import {prepareFieldingExecution,acceptFieldingExecution} from './FieldingExecution';
import {prepareEmotionExecution} from '../execution/ExecutionPreparation';
import {acceptEmotionExecution} from '../execution/ExecutionAcceptance';
import {fixture,change,value} from './FieldingFixtures.test-support';
describe('fielding boundary adversarial regression',()=>{
 it('rejects zero velocity caused by underflow despite positive claimed release speed',()=>{const r=change(fixture(),d=>{d.source.target.x=1e300;d.source.physicalSpeedCeilingMps=1e-100;d.source.profiles=[{profileId:'tiny',minimumAggression:0,motorDurationTicks:1,calibration:{minimumReleaseSpeedMps:1e-100,maximumReleaseSpeedMps:1e-100,minimumTargetErrorMeters:0,maximumTargetErrorMeters:0}}];});assert.equal(prepareFieldingExecution(r).ok,false);});
 it('rejects a motor tick overflow before returning a launch',()=>{const r=change(fixture(),d=>{d.source.transfer.minimumTransferDelayTicks=Number.MAX_SAFE_INTEGER;d.source.transfer.maximumTransferDelayTicks=Number.MAX_SAFE_INTEGER;});assert.equal(prepareFieldingExecution(r).ok,false);});
 it('rejects a first-step tick overflow',()=>{const r=change(fixture('REPLAN'),d=>d.source.firstStep.fixedMotorOffsetTicks=Number.MAX_SAFE_INTEGER);assert.equal(prepareFieldingExecution(r).ok,false);});
 it('rejects world revision overflow on adoption',()=>{const r=change(fixture(),d=>{d.currentFrame.worldRevision=Number.MAX_SAFE_INTEGER;d.source.frame.worldRevision=Number.MAX_SAFE_INTEGER;});const p=value(prepareFieldingExecution(r));assert.equal(acceptFieldingExecution(r,p).ok,false);});
 it('does not invoke a hostile source getter',()=>{const r:any=fixture();let called=0;Object.defineProperty(r.source,'origin',{enumerable:true,get(){called++;return {x:0,y:1,z:0};}});assert.equal(prepareFieldingExecution(r).ok,false);assert.equal(called,0);});
 it('does not invoke a submitted proposal getter',()=>{const r=fixture(),p:any={...value(prepareFieldingExecution(r))};let called=0;Object.defineProperty(p,'plan',{enumerable:true,get(){called++;return null;}});assert.equal(acceptFieldingExecution(r,p).ok,false);assert.equal(called,0);});
 it('rejects cyclic data',()=>{const r:any=fixture();r.source.origin=r;assert.equal(prepareFieldingExecution(r).ok,false);});
 it('rejects sparse profile arrays',()=>{const r:any=fixture();delete r.source.profiles[0];assert.equal(prepareFieldingExecution(r).ok,false);});
 it('rejects symbol metadata rather than silently ignoring it',()=>{const r:any=fixture();r.source[Symbol('extra')]=1;assert.equal(prepareFieldingExecution(r).ok,false);});
 it('rejects unexpected source properties',()=>{const r=change(fixture(),d=>d.source.result='OUT');assert.equal(prepareFieldingExecution(r).ok,false);});
 it('rejects a future possession event',()=>{const r=change(fixture(),d=>d.source.securedPossessionTick=141);assert.equal(prepareFieldingExecution(r).ok,false);});
 it('rejects nonfinite target positions',()=>{const r=change(fixture(),d=>d.source.target.x=Infinity);assert.equal(prepareFieldingExecution(r).ok,false);});
 it('rejects an unbounded target difference',()=>{const r=change(fixture(),d=>{d.source.origin.x=-Number.MAX_VALUE;d.source.target.x=Number.MAX_VALUE;});assert.equal(prepareFieldingExecution(r).ok,false);});
 it('rejects a negative throwing error calibration',()=>{const r=change(fixture(),d=>d.source.profiles[0].calibration.minimumTargetErrorMeters=-1);assert.equal(prepareFieldingExecution(r).ok,false);});
 it('rejects inverted transfer bounds',()=>{const r=change(fixture(),d=>d.source.transfer.minimumTransferDelayTicks=40);assert.equal(prepareFieldingExecution(r).ok,false);});
 it('rejects noninteger commitment clock',()=>{const r=change(fixture(),d=>d.currentFrame.time.tick=140.5);assert.equal(prepareFieldingExecution(r).ok,false);});
 it('does not accept an expired source',()=>{const r=change(fixture(),d=>d.source.validUntilTick=139);assert.equal(prepareFieldingExecution(r).ok,false);});
 it('does not give an already missed input a new physical deadline',()=>{const r=fixture('THROW','SUPERIORITY',{throwIntentShiftTicks:100}),p=value(prepareFieldingExecution(r));assert.equal(p.status,'MISSED_WINDOW');assert.equal(p.plan,null);});
 it('changing unrelated swing timing does not modify the throw plan',()=>{const n=value(prepareFieldingExecution(fixture())),p=value(prepareFieldingExecution(fixture('THROW','ANGER',{swingDecisionShiftTicks:10})));assert.deepEqual(p.plan,n.plan);});
 it('subthreshold appraisal changes do not modify physical results',()=>{const normal=fixture(),r=fixture('THROW','ANGER',{throwAggressionDelta:0.5});const base=change(r.acceptedExecution.proposal.request,d=>{for(const row of d.appraisal.model.rows)row.bias=0.01;});const p=value(prepareEmotionExecution(base)),a=value(acceptEmotionExecution(base,p));const next=change(r,d=>{d.acceptedExecution=a;d.currentEmotion=p.appraisal.state;});assert.equal(p.appraisal.influence.effects,null);assert.deepEqual(value(prepareFieldingExecution(next)).plan,value(prepareFieldingExecution(normal)).plan);});
 it('untrusted changes of source revision reject at final adoption',()=>{const r=fixture(),p=value(prepareFieldingExecution(r)),current=change(r,d=>d.source.revision++);assert.equal(acceptFieldingExecution(current,p).ok,false);});
 it('untrusted physical-model changes reject at final adoption',()=>{const r=fixture(),p=value(prepareFieldingExecution(r)),current=change(r,d=>d.source.repertoireVersion='new');assert.equal(acceptFieldingExecution(current,p).ok,false);});
 it('re-delivery with a different source ID retains the same deduplication key',()=>{const r=fixture(),x=change(r,d=>d.source.sourceId='replacement'),a=value(acceptFieldingExecution(r,value(prepareFieldingExecution(r)))),b=value(acceptFieldingExecution(x,value(prepareFieldingExecution(x))));assert.equal(a.actionKey,b.actionKey);});
 it('does not let another context inherit a known action',()=>{const r=fixture(),p=value(prepareFieldingExecution(r)),x=change(r,d=>{d.currentFrame.contextId='new';d.source.frame.contextId='new';});assert.equal(acceptFieldingExecution(x,p).ok,false);});
 it('rejects an impossible future last-decision tick',()=>{const r=change(fixture('REPLAN'),d=>d.source.lastDecisionTick=200);assert.equal(prepareFieldingExecution(r).ok,false);});
 it('rejects NaN or negative candidate priorities',()=>{for(const n of [NaN,-1]){const r=change(fixture('REPLAN'),d=>d.source.candidates[0].localPriority=n);assert.equal(prepareFieldingExecution(r).ok,false);}});
 it('rejects duplicate candidate evidence labels',()=>{const r=change(fixture('REPLAN'),d=>d.source.candidates[0].evidenceKinds=['same','same']);assert.equal(prepareFieldingExecution(r).ok,false);});
 it('rejects zero integration step',()=>{const r=change(fixture('REPLAN'),d=>d.source.motion.maxIntegrationStepTicks=0);assert.equal(prepareFieldingExecution(r).ok,false);});
 it('rejects inverted first-step delays',()=>{const r=change(fixture('REPLAN'),d=>d.source.firstStep.minimumFirstStepDelayTicks=40);assert.equal(prepareFieldingExecution(r).ok,false);});
 it('replan receipt retains the exact unchanged gate revision',()=>{const r=fixture('REPLAN'),a=value(acceptFieldingExecution(r,value(prepareFieldingExecution(r))));assert.equal(a.emotionRevision,r.currentEmotion.revision);assert.deepEqual(a.proposal.request.currentEmotion,r.currentEmotion);});
});
