import assert from 'node:assert/strict';
import test from 'node:test';
import { assertInheritedOfficialEvidence } from './inherited-official-evidence.mjs';
import { fixture, clone } from './inherited-official-fixture.test-support.mjs';
const sha = character => character.repeat(64);
test('accepts a checked official handoff as inherited evidence without executing an official helper', () => assert.doesNotThrow(() => assertInheritedOfficialEvidence(fixture())));
const negatives = [
  ['unpassed outer attempt', x => x.outerTerminal.passed = false],
  ['truthy outer pass flag', x => x.outerTerminal.passed = 1],
  ['nonzero actual supervisor exit', x => x.outerTerminal.supervisorExitCode = 1],
  ['outer guard trip', x => x.outerTerminal.outerGuard = 'wall'],
  ['outer validation error', x => x.outerTerminal.error = 'missing handoff'],
  ['unreaped supervisor', x => x.outerTerminal.supervisorReaped = false],
  ['remaining execution worker', x => x.outerTerminal.remainingExecutionGroup = [42]],
  ['remaining supervisor', x => x.outerTerminal.remainingSupervisorGroup = [43]],
  ['smoke substituted for official', x => x.outerTerminal.kind = 'smoke'],
  ['mismatched handoff hash in outer receipt', x => x.outerTerminal.references['official-handoff.json'].sha256 = sha('0')],
  ['supervisor runtime receipt invalid', x => x.supervisorTerminal.executingProcessReceiptValid = false],
  ['supervisor did not audit inputs', x => x.supervisorTerminal.sourceInputAndReceiptAudit.passed = false],
  ['supervisor guard trip', x => x.supervisorTerminal.guard = { reason: 'rss' }],
  ['supervisor nonzero exit', x => x.supervisorTerminal.exitCode = 1],
  ['supervisor remaining worker', x => x.supervisorTerminal.remainingOwnedProcesses = [5]],
  ['supervisor reports whole run passed', x => x.supervisorTerminal.status = 'passed'],
  ['unexpected handoff schema', x => x.officialHandoff.schema = 'publication_projection'],
  ['whole-pipeline claim in partial handoff', x => x.officialHandoff.wholePipelinePassed = true],
  ['downstream stages marked complete', x => x.officialHandoff.remainingStages = []],
  ['handoff from another producer', x => x.officialHandoff.physicalProducerReference.outputSha256 = sha('0')],
  ['handoff names a different closure', x => x.officialHandoff.closureSourceId = 'other'],
  ['handoff names a different application', x => x.officialHandoff.applicationId = 'other'],
  ['unpassed official receipt', x => x.officialReceipt.status = 'pending'],
  ['wrong receipt schema', x => x.officialReceipt.schema = 'published_receipt'],
  ['missing real adjudication witness', x => x.officialReceipt.faultEvidence.adjudicationDependencyAfterInsert = false],
  ['missing real application witness', x => x.officialReceipt.faultEvidence.officialApplicationAfterInsert = false],
  ['fault checks omitted', x => delete x.officialReceipt.faultChecks],
  ['new pitch disguised as official', x => x.officialReceipt.executed.newPhysicalPitchActions = 1],
  ['official helper did not execute', x => x.officialReceipt.executed.helperCalls = 0],
  ['official stage repeated', x => x.officialReceipt.counts.officialCompleted = 2],
  ['downstream helper counted in official proof', x => x.stageTerminal.counts.roleStarted = 1],
  ['stage scopes differ', x => x.stageTerminal.executionScope = 'all'],
  ['unclosed stage handles', x => x.stageTerminal.openSqliteHandles = [{ fd: 8 }]],
  ['extra stage receipt', x => x.stageTerminal.phaseReceipts.push({ stage: '02-role-workload', ...x.config.inheritedOfficial.files.receipt })],
  ['changed original physical bytes', x => x.officialReceipt.originalPhysicalArtifactSha256 = sha('0')],
  ['source changed during official stage', x => x.stageTerminal.sourceCutUnchanged = false],
  ['output hash differs from pinned artifact', x => x.officialReceipt.output.sha256 = sha('0')],
  ['output path differs from pinned artifact', x => x.officialHandoff.output.path = '/other.sqlite'],
  ['output WAL is nonempty', x => x.observed.outputWalBytes = 1],
  ['output WAL metadata is unknown', x => delete x.observed.outputWalBytes],
  ['a pinned file changed', x => x.observed.hashes.supervisorTerminal = sha('0')],
  ['prior Source files changed', x => x.observed.priorSourceFilesUnchanged = false],
  ['prior config changed Source identity', x => x.priorConfig.sourceCommit = 'f'.repeat(40)],
  ['prior manifest changed Source identity', x => x.priorSourceManifest.sourceCommit = 'f'.repeat(40)],
  ['prior manifest has duplicate Source paths', x => x.priorSourceManifest.files.push(clone(x.priorSourceManifest.files[0]))],
  ['production owner changed between stages', x => x.currentSourceManifest.files[0].sha256 = sha('0')],
  ['production owner missing in new cut', x => x.currentSourceManifest.files.shift()],
  ['files have colliding paths', x => x.config.inheritedOfficial.files.outerTerminal.path = x.config.inheritedOfficial.files.handoff.path],
  ['file pin is not absolute', x => x.config.inheritedOfficial.files.receipt.path = 'receipt.json'],
];
for (const [name, mutate] of negatives) test(`rejects ${name}`, () => { const value = fixture(); mutate(value); assert.throws(() => assertInheritedOfficialEvidence(value)); });
test('absence of WAL is explicit and permitted', () => { const value = fixture(); value.observed.outputWalBytes = null; assert.doesNotThrow(() => assertInheritedOfficialEvidence(value)); });

// Additional pre-execution boundaries for the still-unwired consumer.
const strongerNegatives = [
  ["missing handoff pin", x => { delete x.config.inheritedOfficial.files.handoff; }],
  ["malformed handoff hash", x => { x.config.inheritedOfficial.files.handoff.sha256 = "bad"; }],
  ["independent handoff hash mismatch", x => { x.observed.hashes.handoff = sha("0"); }],
  ["missing outerTerminal pin", x => { delete x.config.inheritedOfficial.files.outerTerminal; }],
  ["malformed outerTerminal hash", x => { x.config.inheritedOfficial.files.outerTerminal.sha256 = "bad"; }],
  ["independent outerTerminal hash mismatch", x => { x.observed.hashes.outerTerminal = sha("0"); }],
  ["missing stageTerminal pin", x => { delete x.config.inheritedOfficial.files.stageTerminal; }],
  ["malformed stageTerminal hash", x => { x.config.inheritedOfficial.files.stageTerminal.sha256 = "bad"; }],
  ["independent stageTerminal hash mismatch", x => { x.observed.hashes.stageTerminal = sha("0"); }],
  ["missing supervisorTerminal pin", x => { delete x.config.inheritedOfficial.files.supervisorTerminal; }],
  ["malformed supervisorTerminal hash", x => { x.config.inheritedOfficial.files.supervisorTerminal.sha256 = "bad"; }],
  ["independent supervisorTerminal hash mismatch", x => { x.observed.hashes.supervisorTerminal = sha("0"); }],
  ["missing receipt pin", x => { delete x.config.inheritedOfficial.files.receipt; }],
  ["malformed receipt hash", x => { x.config.inheritedOfficial.files.receipt.sha256 = "bad"; }],
  ["independent receipt hash mismatch", x => { x.observed.hashes.receipt = sha("0"); }],
  ["missing configuration pin", x => { delete x.config.inheritedOfficial.files.configuration; }],
  ["malformed configuration hash", x => { x.config.inheritedOfficial.files.configuration.sha256 = "bad"; }],
  ["independent configuration hash mismatch", x => { x.observed.hashes.configuration = sha("0"); }],
  ["missing sourceManifest pin", x => { delete x.config.inheritedOfficial.files.sourceManifest; }],
  ["malformed sourceManifest hash", x => { x.config.inheritedOfficial.files.sourceManifest.sha256 = "bad"; }],
  ["independent sourceManifest hash mismatch", x => { x.observed.hashes.sourceManifest = sha("0"); }],
  ["missing artifact pin", x => { delete x.config.inheritedOfficial.files.artifact; }],
  ["malformed artifact hash", x => { x.config.inheritedOfficial.files.artifact.sha256 = "bad"; }],
  ["independent artifact hash mismatch", x => { x.observed.hashes.artifact = sha("0"); }],
  ["outer path for official-handoff.json substituted", x => { x.outerTerminal.references["official-handoff.json"].path = "/different/file.json"; }],
  ["outer reference for official-handoff.json absent", x => { delete x.outerTerminal.references["official-handoff.json"]; }],
  ["outer path for process-terminal.json substituted", x => { x.outerTerminal.references["process-terminal.json"].path = "/different/file.json"; }],
  ["outer reference for process-terminal.json absent", x => { delete x.outerTerminal.references["process-terminal.json"]; }],
  ["outer path for terminal.json substituted", x => { x.outerTerminal.references["terminal.json"].path = "/different/file.json"; }],
  ["outer reference for terminal.json absent", x => { delete x.outerTerminal.references["terminal.json"]; }],
  ["officialHandoff sourceRoot differs", x => { x.officialHandoff.sourceIdentity.sourceRoot = "/different/source"; }],
  ["officialHandoff sourceCommit differs", x => { x.officialHandoff.sourceIdentity.sourceCommit = "f".repeat(40); }],
  ["officialHandoff sourceTree differs", x => { x.officialHandoff.sourceIdentity.sourceTree = "f".repeat(40); }],
  ["officialHandoff sourceManifestSha256 differs", x => { x.officialHandoff.sourceIdentity.sourceManifestSha256 = sha("0"); }],
  ["officialReceipt sourceRoot differs", x => { x.officialReceipt.sourceIdentity.sourceRoot = "/different/source"; }],
  ["officialReceipt sourceCommit differs", x => { x.officialReceipt.sourceIdentity.sourceCommit = "f".repeat(40); }],
  ["officialReceipt sourceTree differs", x => { x.officialReceipt.sourceIdentity.sourceTree = "f".repeat(40); }],
  ["officialReceipt sourceManifestSha256 differs", x => { x.officialReceipt.sourceIdentity.sourceManifestSha256 = sha("0"); }],
  ["stageTerminal sourceRoot differs", x => { x.stageTerminal.sourceIdentity.sourceRoot = "/different/source"; }],
  ["stageTerminal sourceCommit differs", x => { x.stageTerminal.sourceIdentity.sourceCommit = "f".repeat(40); }],
  ["stageTerminal sourceTree differs", x => { x.stageTerminal.sourceIdentity.sourceTree = "f".repeat(40); }],
  ["stageTerminal sourceManifestSha256 differs", x => { x.stageTerminal.sourceIdentity.sourceManifestSha256 = sha("0"); }],
  ["outer sourceCommit differs", x => { x.outerTerminal.sourceCommit = sha("0"); }],
  ["outer sourceManifestSha256 differs", x => { x.outerTerminal.sourceManifestSha256 = sha("0"); }],
  ["outer configSha256 differs", x => { x.outerTerminal.configSha256 = sha("0"); }],
  ["officialHandoff raw publication marker publicationProjection", x => { x.officialHandoff.publicationProjection = true; }],
  ["officialHandoff raw publication marker originalRawReceiptSha256", x => { x.officialHandoff.originalRawReceiptSha256 = true; }],
  ["officialReceipt raw publication marker publicationProjection", x => { x.officialReceipt.publicationProjection = true; }],
  ["officialReceipt raw publication marker originalRawReceiptSha256", x => { x.officialReceipt.originalRawReceiptSha256 = true; }],
  ["stageTerminal raw publication marker publicationProjection", x => { x.stageTerminal.publicationProjection = true; }],
  ["stageTerminal raw publication marker originalRawReceiptSha256", x => { x.stageTerminal.originalRawReceiptSha256 = true; }],
  ["supervisorTerminal raw publication marker publicationProjection", x => { x.supervisorTerminal.publicationProjection = true; }],
  ["supervisorTerminal raw publication marker originalRawReceiptSha256", x => { x.supervisorTerminal.originalRawReceiptSha256 = true; }],
  ["outerTerminal raw publication marker publicationProjection", x => { x.outerTerminal.publicationProjection = true; }],
  ["outerTerminal raw publication marker originalRawReceiptSha256", x => { x.outerTerminal.originalRawReceiptSha256 = true; }],
  ["officialReceipt boolean count", x => { x.officialReceipt.counts.officialCompleted = true; }],
  ["officialReceipt extra count", x => { x.officialReceipt.counts.invented = 0; }],
  ["officialReceipt missing count", x => { delete x.officialReceipt.counts.nextCompleted; }],
  ["stageTerminal boolean count", x => { x.stageTerminal.counts.officialCompleted = true; }],
  ["stageTerminal extra count", x => { x.stageTerminal.counts.invented = 0; }],
  ["stageTerminal missing count", x => { delete x.stageTerminal.counts.nextCompleted; }],
  ["supervisor status differs", x => { x.supervisorTerminal.status = "pending"; }],
  ["supervisor executionScope differs", x => { x.supervisorTerminal.executionScope = "all"; }],
  ["supervisor wholePipelinePassed differs", x => { x.supervisorTerminal.wholePipelinePassed = true; }],
  ["supervisor pipelineTerminalStatus differs", x => { x.supervisorTerminal.pipelineTerminalStatus = "passed"; }],
  ["supervisor audited receipt hash differs", x => { x.supervisorTerminal.sourceInputAndReceiptAudit.preservedPhaseReceipts[0].sha256 = sha("0"); }],
  ["supervisor listed receipt path differs", x => { x.supervisorTerminal.preservedPhaseReceipts[0] = "/other/01-official.receipt.json"; }],
  ["handoff config path differs", x => { x.officialHandoff.config.path = "/other.json"; }],
  ["handoff config hash differs", x => { x.officialHandoff.config.sha256 = sha("0"); }],
  ["handoff officialReceipt path differs", x => { x.officialHandoff.officialReceipt.path = "/other.json"; }],
  ["handoff officialReceipt hash differs", x => { x.officialHandoff.officialReceipt.sha256 = sha("0"); }],
  ["handoff stageTerminal path differs", x => { x.officialHandoff.stageTerminal.path = "/other.json"; }],
  ["handoff stageTerminal hash differs", x => { x.officialHandoff.stageTerminal.sha256 = sha("0"); }],
  ["handoff supervisorTerminal path differs", x => { x.officialHandoff.supervisorTerminal.path = "/other.json"; }],
  ["handoff supervisorTerminal hash differs", x => { x.officialHandoff.supervisorTerminal.sha256 = sha("0"); }],
  ["officialReceipt output realDisk invalid", x => { x.officialReceipt.output.realDisk = false; }],
  ["officialReceipt output mainFilename invalid", x => { x.officialReceipt.output.mainFilename = "/wrong.sqlite"; }],
  ["officialReceipt output journalMode invalid", x => { x.officialReceipt.output.journalMode = "delete"; }],
  ["officialReceipt output wrapperReadOnlyOpenClosedVerified invalid", x => { x.officialReceipt.output.wrapperReadOnlyOpenClosedVerified = false; }],
  ["officialReceipt output count applications differs", x => { x.officialReceipt.output.rowCounts.applications = 2; }],
  ["officialReceipt output count physical_pitch_progress_actions differs", x => { x.officialReceipt.output.rowCounts.physical_pitch_progress_actions = 2; }],
  ["officialReceipt output count world_player_workload_activities differs", x => { x.officialReceipt.output.rowCounts.world_player_workload_activities = 1; }],
  ["officialHandoff output realDisk invalid", x => { x.officialHandoff.output.realDisk = false; }],
  ["officialHandoff output mainFilename invalid", x => { x.officialHandoff.output.mainFilename = "/wrong.sqlite"; }],
  ["officialHandoff output journalMode invalid", x => { x.officialHandoff.output.journalMode = "delete"; }],
  ["officialHandoff output wrapperReadOnlyOpenClosedVerified invalid", x => { x.officialHandoff.output.wrapperReadOnlyOpenClosedVerified = false; }],
  ["officialHandoff output count applications differs", x => { x.officialHandoff.output.rowCounts.applications = 2; }],
  ["officialHandoff output count physical_pitch_progress_actions differs", x => { x.officialHandoff.output.rowCounts.physical_pitch_progress_actions = 2; }],
  ["officialHandoff output count world_player_workload_activities differs", x => { x.officialHandoff.output.rowCounts.world_player_workload_activities = 1; }],
  ["official inserted no application", x => { x.officialReceipt.executed.newOfficialApplications = 0; }],
  ["official synthetic policy provenance omitted", x => { delete x.officialReceipt.syntheticFixturePolicy; }],
  ["stage status differs", x => { x.stageTerminal.status = "passed"; }],
  ["stage wholePipelinePassed differs", x => { x.stageTerminal.wholePipelinePassed = true; }],
  ["stage remainingStages differs", x => { x.stageTerminal.remainingStages = []; }],
  ["stage physicalSourceUnchanged differs", x => { x.stageTerminal.physicalSourceUnchanged = false; }],
  ["stage scoringStillUnsupported differs", x => { x.stageTerminal.scoringStillUnsupported = false; }],
  ["stage actualRoleWorkloadStillPending differs", x => { x.stageTerminal.actualRoleWorkloadStillPending = false; }],
  ["stage newPhysicalPitchActions differs", x => { x.stageTerminal.newPhysicalPitchActions = 1; }],
  ["resumable closureSourceId differs", x => { x.stageTerminal.resumableOfficial.closureSourceId = "other"; }],
  ["resumable applicationId differs", x => { x.stageTerminal.resumableOfficial.applicationId = "other"; }],
  ["resumable receipt reference differs", x => { x.stageTerminal.resumableOfficial.receipt.sha256 = sha("0"); }],
  ["resumable output differs", x => { x.stageTerminal.resumableOfficial.output.sha256 = sha("0"); }],
  ["prior config schema differs", x => { x.priorConfig.schema = "wrong"; }],
  ["prior config executionScope differs", x => { x.priorConfig.executionScope = "all"; }],
  ["prior config faultChecks differs", x => { x.priorConfig.faultChecks = false; }],
  ["prior config executeNextPitch differs", x => { x.priorConfig.executeNextPitch = false; }],
  ["prior config physicalArtifactSha256 differs", x => { x.priorConfig.physicalArtifactSha256 = sha("0"); }],
  ["prior config physicalEvidenceSha256 differs", x => { x.priorConfig.physicalEvidenceSha256 = sha("0"); }],
  ["prior config physicalEndSourceId differs", x => { x.priorConfig.physicalEndSourceId = "different"; }],
  ["wrong inherited contract kind", x => { x.config.inheritedOfficial.kind = "unchecked"; }],
  ["current continuation scope is official", x => { x.config.executionScope = "official"; }],
  ["current physical producer differs", x => { x.config.physicalProducer.kind = "different"; }],
  ["current ended database differs", x => { x.config.physicalArtifactSha256 = sha("0"); }],
  ["current official Source pin differs", x => { x.config.inheritedOfficial.sourceCommit = "f".repeat(40); }],
  ["current official Source root differs", x => { x.config.inheritedOfficial.sourceRoot = "/other/source"; }],
  ["current official Source manifest pin differs", x => { x.config.inheritedOfficial.sourceManifestSha256 = sha("0"); }],
  ["prior manifest invalid schema", x => { x.priorSourceManifest.schema = "projection"; }],
  ["prior manifest Source root differs", x => { x.priorSourceManifest.sourceRoot = "/other/source"; }],
  ["prior manifest Source tree differs", x => { x.priorSourceManifest.sourceTree = "f".repeat(40); }],
  ["prior manifest absolute Source path", x => { x.priorSourceManifest.files[0].path = "/src/owner.ts"; }],
  ["prior manifest traversal Source path", x => { x.priorSourceManifest.files[0].path = "src/../owner.ts"; }],
  ["prior manifest malformed file hash", x => { x.priorSourceManifest.files[0].sha256 = "bad"; }],
  ["duplicate current Source paths", x => { x.currentSourceManifest.files.push(clone(x.currentSourceManifest.files[0])); }],
  ["new production owner introduced between stages", x => { x.currentSourceManifest.files.push({path:"src/new-owner.ts",sha256:sha("0")}); }],
  ["current manifest Source commit mismatches current config", x => { x.currentSourceManifest.sourceCommit = "f".repeat(40); }],
  ["current manifest Source root mismatches current config", x => { x.currentSourceManifest.sourceRoot = "/different/source"; }],
  ["unknown prior Source preservation state", x => { delete x.observed.priorSourceFilesUnchanged; }],
  ["unexpected inherited file role", x => { x.config.inheritedOfficial.files.guessed = {path:"/guess.json",sha256:sha("0")}; }],
  ["unnormalized inherited file path", x => { x.config.inheritedOfficial.files.receipt.path = "/prior/../receipt.json"; }],
];
for (const [name, mutate] of strongerNegatives) test(`rejects ${name}`, () => { const value = fixture(); mutate(value); assert.throws(() => assertInheritedOfficialEvidence(value)); });

test('accepts the explicit separately admitted known-profile producer lineage', () => {
  const value = fixture();
  for (const target of [value.producerReference, value.config.physicalProducer, value.priorConfig.physicalProducer,
    value.officialHandoff.physicalProducerReference, value.officialReceipt.physicalProducerReference]) target.kind = 'first_base_known_profile_producer_v1';
  assert.doesNotThrow(() => assertInheritedOfficialEvidence(value));
});
