import assert from 'node:assert/strict';
import test from 'node:test';
import { assertOfficialReadReplayInput, assertOfficialReadReplayEvidence } from './official-read-replay-evidence.mjs';
import { assertInheritedOfficialEvidence } from './inherited-official-evidence.mjs';
import { fixture, inputFixture, repinPasses, OWNER, BEFORE } from './official-read-replay-fixture.test-support.mjs';
const clone = value => structuredClone(value);
const set = (value, path, changed) => { const keys=path.split('.'), last=keys.pop(); let target=value; for(const key of keys) target=target[key]; target[last]=changed; };
// The original RED count included two no-op configuration mutations. Those are
// superseded as invalid controls, not evidence of a missing configuration check.
const rejectInput = (name, mutate) => test(`input: ${name}`,()=>{const value=inputFixture(),before=clone(value);mutate(value);assert.notDeepStrictEqual(value,before,'rejection control must actually mutate its input');assert.throws(()=>assertOfficialReadReplayInput(value));});
const rejectReceipt = (name, mutate) => test(`receipt: ${name}`,()=>{const value=fixture(),before=clone(value);mutate(value);assert.notDeepStrictEqual(value,before,'rejection control must actually mutate its input');assert.throws(()=>assertOfficialReadReplayEvidence(value));});
test('admits the explicit invented replay input',()=>assert.doesNotThrow(()=>assertOfficialReadReplayInput(inputFixture())));
test('admits a reviewed documentation-only input difference',()=>{const v=inputFixture();v.currentSourceManifest.files.push({path:'docs/review.md',sha256:'f'.repeat(64)});v.officialEvidence.currentSourceManifest=clone(v.currentSourceManifest);assert.doesNotThrow(()=>assertOfficialReadReplayInput(v));});
test('admits a complete invented role-consumed replay',()=>assert.doesNotThrow(()=>assertOfficialReadReplayEvidence(fixture())));
test('admits the same replay proof for next-stage provenance',()=>{const v=fixture();v.config.executionScope='next';v.officialEvidence.config=clone(v.config);assert.doesNotThrow(()=>assertOfficialReadReplayEvidence(v));});
test('ordinary inherited continuity still rejects the changed production owner',()=>assert.throws(()=>assertInheritedOfficialEvidence(fixture().officialEvidence),/production Source continuity/));
test('ordinary original-stage provenance still accepts its unchanged production bytes',()=>{const v=fixture().officialEvidence;v.currentSourceManifest.files.find(row=>row.path===OWNER).sha256=BEFORE;assert.doesNotThrow(()=>assertInheritedOfficialEvidence(v));});
rejectInput("rejects transition kind",v=>{v.config.sourceTransition.kind = 'foreign';});
rejectReceipt("rejects transition kind",v=>{v.config.sourceTransition.kind = 'foreign';});
rejectInput("rejects transition purpose",v=>{v.config.sourceTransition.purpose = 'foreign';});
rejectReceipt("rejects transition purpose",v=>{v.config.sourceTransition.purpose = 'foreign';});
rejectInput("rejects transition fromSourceIdentity sourceRoot",v=>{v.config.sourceTransition.fromSourceIdentity.sourceRoot = '/foreign/source';});
rejectReceipt("rejects transition fromSourceIdentity sourceRoot",v=>{v.config.sourceTransition.fromSourceIdentity.sourceRoot = '/foreign/source';});
rejectInput("rejects transition fromSourceIdentity sourceCommit",v=>{v.config.sourceTransition.fromSourceIdentity.sourceCommit = 'f'.repeat(40);});
rejectReceipt("rejects transition fromSourceIdentity sourceCommit",v=>{v.config.sourceTransition.fromSourceIdentity.sourceCommit = 'f'.repeat(40);});
rejectInput("rejects transition fromSourceIdentity sourceTree",v=>{v.config.sourceTransition.fromSourceIdentity.sourceTree = 'f'.repeat(40);});
rejectReceipt("rejects transition fromSourceIdentity sourceTree",v=>{v.config.sourceTransition.fromSourceIdentity.sourceTree = 'f'.repeat(40);});
rejectInput("rejects transition fromSourceIdentity sourceManifestSha256",v=>{v.config.sourceTransition.fromSourceIdentity.sourceManifestSha256 = 'f'.repeat(64);});
rejectReceipt("rejects transition fromSourceIdentity sourceManifestSha256",v=>{v.config.sourceTransition.fromSourceIdentity.sourceManifestSha256 = 'f'.repeat(64);});
rejectInput("rejects transition toSourceIdentity sourceRoot",v=>{v.config.sourceTransition.toSourceIdentity.sourceRoot = '/foreign/source';});
rejectReceipt("rejects transition toSourceIdentity sourceRoot",v=>{v.config.sourceTransition.toSourceIdentity.sourceRoot = '/foreign/source';});
rejectInput("rejects transition toSourceIdentity sourceCommit",v=>{v.config.sourceTransition.toSourceIdentity.sourceCommit = 'f'.repeat(40);});
rejectReceipt("rejects transition toSourceIdentity sourceCommit",v=>{v.config.sourceTransition.toSourceIdentity.sourceCommit = 'f'.repeat(40);});
rejectInput("rejects transition toSourceIdentity sourceTree",v=>{v.config.sourceTransition.toSourceIdentity.sourceTree = 'f'.repeat(40);});
rejectReceipt("rejects transition toSourceIdentity sourceTree",v=>{v.config.sourceTransition.toSourceIdentity.sourceTree = 'f'.repeat(40);});
rejectInput("rejects transition toSourceIdentity sourceManifestSha256",v=>{v.config.sourceTransition.toSourceIdentity.sourceManifestSha256 = 'f'.repeat(64);});
rejectReceipt("rejects transition toSourceIdentity sourceManifestSha256",v=>{v.config.sourceTransition.toSourceIdentity.sourceManifestSha256 = 'f'.repeat(64);});
rejectInput("rejects repinned different production path",v=>{v.config.sourceTransition.changedProductionFiles[0].path = 'src/foreign-owner.ts'; v.officialEvidence.config.sourceTransition = clone(v.config.sourceTransition);});
rejectReceipt("rejects repinned different production path",v=>{v.config.sourceTransition.changedProductionFiles[0].path = 'src/foreign-owner.ts'; v.officialEvidence.config.sourceTransition = clone(v.config.sourceTransition);});
rejectInput("rejects repinned different production beforeSha256",v=>{v.config.sourceTransition.changedProductionFiles[0].beforeSha256 = 'f'.repeat(64); v.officialEvidence.config.sourceTransition = clone(v.config.sourceTransition);});
rejectReceipt("rejects repinned different production beforeSha256",v=>{v.config.sourceTransition.changedProductionFiles[0].beforeSha256 = 'f'.repeat(64); v.officialEvidence.config.sourceTransition = clone(v.config.sourceTransition);});
rejectInput("rejects repinned different production afterSha256",v=>{v.config.sourceTransition.changedProductionFiles[0].afterSha256 = 'f'.repeat(64); v.officialEvidence.config.sourceTransition = clone(v.config.sourceTransition);});
rejectReceipt("rejects repinned different production afterSha256",v=>{v.config.sourceTransition.changedProductionFiles[0].afterSha256 = 'f'.repeat(64); v.officialEvidence.config.sourceTransition = clone(v.config.sourceTransition);});
rejectInput("rejects no production transition",v=>{v.config.sourceTransition.changedProductionFiles = [];});
rejectReceipt("rejects no production transition",v=>{v.config.sourceTransition.changedProductionFiles = [];});
rejectInput("rejects duplicate production transition",v=>{v.config.sourceTransition.changedProductionFiles.push(clone(v.config.sourceTransition.changedProductionFiles[0]));});
rejectReceipt("rejects duplicate production transition",v=>{v.config.sourceTransition.changedProductionFiles.push(clone(v.config.sourceTransition.changedProductionFiles[0]));});
rejectInput("rejects extra current production path",v=>{v.currentSourceManifest.files.push({path:'src/extra-owner.ts',sha256:'f'.repeat(64)});});
rejectReceipt("rejects extra current production path",v=>{v.currentSourceManifest.files.push({path:'src/extra-owner.ts',sha256:'f'.repeat(64)});});
rejectInput("rejects removed current production path",v=>{v.currentSourceManifest.files = v.currentSourceManifest.files.filter(row=>row.path !== 'src/owner.ts');});
rejectReceipt("rejects removed current production path",v=>{v.currentSourceManifest.files = v.currentSourceManifest.files.filter(row=>row.path !== 'src/owner.ts');});
rejectInput("rejects changed unrelated current production bytes",v=>{v.currentSourceManifest.files.find(row=>row.path==='src/owner.ts').sha256='f'.repeat(64);});
rejectReceipt("rejects changed unrelated current production bytes",v=>{v.currentSourceManifest.files.find(row=>row.path==='src/owner.ts').sha256='f'.repeat(64);});
rejectInput("rejects missing repaired owner",v=>{v.currentSourceManifest.files = v.currentSourceManifest.files.filter(row=>row.path!==OWNER);});
rejectReceipt("rejects missing repaired owner",v=>{v.currentSourceManifest.files = v.currentSourceManifest.files.filter(row=>row.path!==OWNER);});
rejectInput("rejects unchanged old owner masquerading as repair",v=>{v.currentSourceManifest.files.find(row=>row.path===OWNER).sha256=BEFORE;});
rejectReceipt("rejects unchanged old owner masquerading as repair",v=>{v.currentSourceManifest.files.find(row=>row.path===OWNER).sha256=BEFORE;});
rejectInput("rejects unreviewed repaired owner bytes",v=>{v.currentSourceManifest.files.find(row=>row.path===OWNER).sha256='f'.repeat(64);});
rejectReceipt("rejects unreviewed repaired owner bytes",v=>{v.currentSourceManifest.files.find(row=>row.path===OWNER).sha256='f'.repeat(64);});
rejectInput("rejects original owner before bytes drift",v=>{v.officialEvidence.priorSourceManifest.files.find(row=>row.path===OWNER).sha256='f'.repeat(64);});
rejectReceipt("rejects original owner before bytes drift",v=>{v.officialEvidence.priorSourceManifest.files.find(row=>row.path===OWNER).sha256='f'.repeat(64);});
rejectInput("rejects duplicated manifest owner",v=>{v.currentSourceManifest.files.push(clone(v.currentSourceManifest.files[0]));});
rejectReceipt("rejects duplicated manifest owner",v=>{v.currentSourceManifest.files.push(clone(v.currentSourceManifest.files[0]));});
rejectInput("rejects parent-relative Source path",v=>{v.currentSourceManifest.files[0].path='../outside.ts';});
rejectReceipt("rejects parent-relative Source path",v=>{v.currentSourceManifest.files[0].path='../outside.ts';});
rejectInput("rejects current Source sourceRoot",v=>{v.currentSourceManifest.sourceRoot = '/foreign';});
rejectReceipt("rejects current Source sourceRoot",v=>{v.currentSourceManifest.sourceRoot = '/foreign';});
rejectInput("rejects current Source sourceCommit",v=>{v.currentSourceManifest.sourceCommit = 'f'.repeat(40);});
rejectReceipt("rejects current Source sourceCommit",v=>{v.currentSourceManifest.sourceCommit = 'f'.repeat(40);});
rejectInput("rejects false current Source byte verification",v=>{v.observed.currentSourceFilesUnchanged = false;});
rejectReceipt("rejects false current Source byte verification",v=>{v.observed.currentSourceFilesUnchanged = false;});
rejectInput("rejects truthy current Source byte verification",v=>{v.observed.currentSourceFilesUnchanged = 'true';});
rejectReceipt("rejects truthy current Source byte verification",v=>{v.observed.currentSourceFilesUnchanged = 'true';});
rejectInput("rejects missing current Source byte verification",v=>{v.observed.currentSourceFilesUnchanged = undefined;});
rejectReceipt("rejects missing current Source byte verification",v=>{v.observed.currentSourceFilesUnchanged = undefined;});
rejectInput("rejects missing original handoff",v=>{delete v.config.inheritedOfficial.files.handoff;});
rejectReceipt("rejects missing original handoff",v=>{delete v.config.inheritedOfficial.files.handoff;});
rejectInput("rejects foreign original handoff",v=>{v.config.inheritedOfficial.files.handoff.path='/foreign/handoff.json';});
rejectReceipt("rejects foreign original handoff",v=>{v.config.inheritedOfficial.files.handoff.path='/foreign/handoff.json';});
rejectInput("rejects changed original handoff observed hash",v=>{v.officialEvidence.observed.hashes.handoff='f'.repeat(64);});
rejectReceipt("rejects changed original handoff observed hash",v=>{v.officialEvidence.observed.hashes.handoff='f'.repeat(64);});
rejectInput("rejects missing original outerTerminal",v=>{delete v.config.inheritedOfficial.files.outerTerminal;});
rejectReceipt("rejects missing original outerTerminal",v=>{delete v.config.inheritedOfficial.files.outerTerminal;});
rejectInput("rejects foreign original outerTerminal",v=>{v.config.inheritedOfficial.files.outerTerminal.path='/foreign/outerTerminal.json';});
rejectReceipt("rejects foreign original outerTerminal",v=>{v.config.inheritedOfficial.files.outerTerminal.path='/foreign/outerTerminal.json';});
rejectInput("rejects changed original outerTerminal observed hash",v=>{v.officialEvidence.observed.hashes.outerTerminal='f'.repeat(64);});
rejectReceipt("rejects changed original outerTerminal observed hash",v=>{v.officialEvidence.observed.hashes.outerTerminal='f'.repeat(64);});
rejectInput("rejects missing original stageTerminal",v=>{delete v.config.inheritedOfficial.files.stageTerminal;});
rejectReceipt("rejects missing original stageTerminal",v=>{delete v.config.inheritedOfficial.files.stageTerminal;});
rejectInput("rejects foreign original stageTerminal",v=>{v.config.inheritedOfficial.files.stageTerminal.path='/foreign/stageTerminal.json';});
rejectReceipt("rejects foreign original stageTerminal",v=>{v.config.inheritedOfficial.files.stageTerminal.path='/foreign/stageTerminal.json';});
rejectInput("rejects changed original stageTerminal observed hash",v=>{v.officialEvidence.observed.hashes.stageTerminal='f'.repeat(64);});
rejectReceipt("rejects changed original stageTerminal observed hash",v=>{v.officialEvidence.observed.hashes.stageTerminal='f'.repeat(64);});
rejectInput("rejects missing original supervisorTerminal",v=>{delete v.config.inheritedOfficial.files.supervisorTerminal;});
rejectReceipt("rejects missing original supervisorTerminal",v=>{delete v.config.inheritedOfficial.files.supervisorTerminal;});
rejectInput("rejects foreign original supervisorTerminal",v=>{v.config.inheritedOfficial.files.supervisorTerminal.path='/foreign/supervisorTerminal.json';});
rejectReceipt("rejects foreign original supervisorTerminal",v=>{v.config.inheritedOfficial.files.supervisorTerminal.path='/foreign/supervisorTerminal.json';});
rejectInput("rejects changed original supervisorTerminal observed hash",v=>{v.officialEvidence.observed.hashes.supervisorTerminal='f'.repeat(64);});
rejectReceipt("rejects changed original supervisorTerminal observed hash",v=>{v.officialEvidence.observed.hashes.supervisorTerminal='f'.repeat(64);});
rejectInput("rejects missing original receipt",v=>{delete v.config.inheritedOfficial.files.receipt;});
rejectReceipt("rejects missing original receipt",v=>{delete v.config.inheritedOfficial.files.receipt;});
rejectInput("rejects foreign original receipt",v=>{v.config.inheritedOfficial.files.receipt.path='/foreign/receipt.json';});
rejectReceipt("rejects foreign original receipt",v=>{v.config.inheritedOfficial.files.receipt.path='/foreign/receipt.json';});
rejectInput("rejects changed original receipt observed hash",v=>{v.officialEvidence.observed.hashes.receipt='f'.repeat(64);});
rejectReceipt("rejects changed original receipt observed hash",v=>{v.officialEvidence.observed.hashes.receipt='f'.repeat(64);});
rejectInput("rejects missing original configuration",v=>{delete v.config.inheritedOfficial.files.configuration;});
rejectReceipt("rejects missing original configuration",v=>{delete v.config.inheritedOfficial.files.configuration;});
rejectInput("rejects foreign original configuration",v=>{v.config.inheritedOfficial.files.configuration.path='/foreign/configuration.json';});
rejectReceipt("rejects foreign original configuration",v=>{v.config.inheritedOfficial.files.configuration.path='/foreign/configuration.json';});
rejectInput("rejects changed original configuration observed hash",v=>{v.officialEvidence.observed.hashes.configuration='0'.repeat(64);});
rejectReceipt("rejects changed original configuration observed hash",v=>{v.officialEvidence.observed.hashes.configuration='0'.repeat(64);});
rejectInput("rejects missing original sourceManifest",v=>{delete v.config.inheritedOfficial.files.sourceManifest;});
rejectReceipt("rejects missing original sourceManifest",v=>{delete v.config.inheritedOfficial.files.sourceManifest;});
rejectInput("rejects foreign original sourceManifest",v=>{v.config.inheritedOfficial.files.sourceManifest.path='/foreign/sourceManifest.json';});
rejectReceipt("rejects foreign original sourceManifest",v=>{v.config.inheritedOfficial.files.sourceManifest.path='/foreign/sourceManifest.json';});
rejectInput("rejects changed original sourceManifest observed hash",v=>{v.officialEvidence.observed.hashes.sourceManifest='f'.repeat(64);});
rejectReceipt("rejects changed original sourceManifest observed hash",v=>{v.officialEvidence.observed.hashes.sourceManifest='f'.repeat(64);});
rejectInput("rejects missing original artifact",v=>{delete v.config.inheritedOfficial.files.artifact;});
rejectReceipt("rejects missing original artifact",v=>{delete v.config.inheritedOfficial.files.artifact;});
rejectInput("rejects foreign original artifact",v=>{v.config.inheritedOfficial.files.artifact.path='/foreign/artifact.json';});
rejectReceipt("rejects foreign original artifact",v=>{v.config.inheritedOfficial.files.artifact.path='/foreign/artifact.json';});
rejectInput("rejects changed original artifact observed hash",v=>{v.officialEvidence.observed.hashes.artifact='f'.repeat(64);});
rejectReceipt("rejects changed original artifact observed hash",v=>{v.officialEvidence.observed.hashes.artifact='f'.repeat(64);});
rejectInput("rejects missing original proof stageTerminal.physicalSourceUnchanged",v=>{set(v.officialEvidence,'stageTerminal.physicalSourceUnchanged',false);});
rejectReceipt("rejects missing original proof stageTerminal.physicalSourceUnchanged",v=>{set(v.officialEvidence,'stageTerminal.physicalSourceUnchanged',false);});
rejectInput("rejects missing original proof stageTerminal.sourceCutUnchanged",v=>{set(v.officialEvidence,'stageTerminal.sourceCutUnchanged',false);});
rejectReceipt("rejects missing original proof stageTerminal.sourceCutUnchanged",v=>{set(v.officialEvidence,'stageTerminal.sourceCutUnchanged',false);});
rejectInput("rejects missing original proof officialReceipt.faultChecks",v=>{set(v.officialEvidence,'officialReceipt.faultChecks',false);});
rejectReceipt("rejects missing original proof officialReceipt.faultChecks",v=>{set(v.officialEvidence,'officialReceipt.faultChecks',false);});
rejectInput("rejects missing original proof officialReceipt.faultEvidence.adjudicationDependencyAfterInsert",v=>{set(v.officialEvidence,'officialReceipt.faultEvidence.adjudicationDependencyAfterInsert',false);});
rejectReceipt("rejects missing original proof officialReceipt.faultEvidence.adjudicationDependencyAfterInsert",v=>{set(v.officialEvidence,'officialReceipt.faultEvidence.adjudicationDependencyAfterInsert',false);});
rejectInput("rejects missing original proof officialReceipt.faultEvidence.officialApplicationAfterInsert",v=>{set(v.officialEvidence,'officialReceipt.faultEvidence.officialApplicationAfterInsert',false);});
rejectReceipt("rejects missing original proof officialReceipt.faultEvidence.officialApplicationAfterInsert",v=>{set(v.officialEvidence,'officialReceipt.faultEvidence.officialApplicationAfterInsert',false);});
rejectInput("rejects missing original proof supervisorTerminal.executingProcessReceiptValid",v=>{set(v.officialEvidence,'supervisorTerminal.executingProcessReceiptValid',false);});
rejectReceipt("rejects missing original proof supervisorTerminal.executingProcessReceiptValid",v=>{set(v.officialEvidence,'supervisorTerminal.executingProcessReceiptValid',false);});
rejectInput("rejects missing original proof supervisorTerminal.sourceInputAndReceiptAudit.passed",v=>{set(v.officialEvidence,'supervisorTerminal.sourceInputAndReceiptAudit.passed',false);});
rejectReceipt("rejects missing original proof supervisorTerminal.sourceInputAndReceiptAudit.passed",v=>{set(v.officialEvidence,'supervisorTerminal.sourceInputAndReceiptAudit.passed',false);});
rejectInput("rejects missing original proof outerTerminal.passed",v=>{set(v.officialEvidence,'outerTerminal.passed',false);});
rejectReceipt("rejects missing original proof outerTerminal.passed",v=>{set(v.officialEvidence,'outerTerminal.passed',false);});
rejectInput("rejects missing original proof outerTerminal.supervisorReaped",v=>{set(v.officialEvidence,'outerTerminal.supervisorReaped',false);});
rejectReceipt("rejects missing original proof outerTerminal.supervisorReaped",v=>{set(v.officialEvidence,'outerTerminal.supervisorReaped',false);});
rejectInput("rejects projected original officialHandoff",v=>{v.officialEvidence.officialHandoff.publicationProjection=false;});
rejectReceipt("rejects projected original officialHandoff",v=>{v.officialEvidence.officialHandoff.publicationProjection=false;});
rejectInput("rejects projected original officialReceipt",v=>{v.officialEvidence.officialReceipt.publicationProjection=false;});
rejectReceipt("rejects projected original officialReceipt",v=>{v.officialEvidence.officialReceipt.publicationProjection=false;});
rejectInput("rejects projected original stageTerminal",v=>{v.officialEvidence.stageTerminal.publicationProjection=false;});
rejectReceipt("rejects projected original stageTerminal",v=>{v.officialEvidence.stageTerminal.publicationProjection=false;});
rejectInput("rejects projected original supervisorTerminal",v=>{v.officialEvidence.supervisorTerminal.publicationProjection=false;});
rejectReceipt("rejects projected original supervisorTerminal",v=>{v.officialEvidence.supervisorTerminal.publicationProjection=false;});
rejectInput("rejects projected original outerTerminal",v=>{v.officialEvidence.outerTerminal.publicationProjection=false;});
rejectReceipt("rejects projected original outerTerminal",v=>{v.officialEvidence.outerTerminal.publicationProjection=false;});
rejectInput("rejects projected original priorConfig",v=>{v.officialEvidence.priorConfig.publicationProjection=false;});
rejectReceipt("rejects projected original priorConfig",v=>{v.officialEvidence.priorConfig.publicationProjection=false;});
rejectInput("rejects projected original priorSourceManifest",v=>{v.officialEvidence.priorSourceManifest.publicationProjection=false;});
rejectReceipt("rejects projected original priorSourceManifest",v=>{v.officialEvidence.priorSourceManifest.publicationProjection=false;});
rejectInput("rejects original supervisor failure",v=>{v.officialEvidence.outerTerminal.supervisorExitCode=1;});
rejectReceipt("rejects original supervisor failure",v=>{v.officialEvidence.outerTerminal.supervisorExitCode=1;});
rejectInput("rejects original unreaped process",v=>{v.officialEvidence.outerTerminal.remainingExecutionGroup=[99];});
rejectReceipt("rejects original unreaped process",v=>{v.officialEvidence.outerTerminal.remainingExecutionGroup=[99];});
rejectInput("rejects original dirty WAL",v=>{v.officialEvidence.observed.outputWalBytes=1;});
rejectReceipt("rejects original dirty WAL",v=>{v.officialEvidence.observed.outputWalBytes=1;});
rejectInput("rejects original Source drift",v=>{v.officialEvidence.observed.priorSourceFilesUnchanged=false;});
rejectReceipt("rejects original Source drift",v=>{v.officialEvidence.observed.priorSourceFilesUnchanged=false;});
rejectInput("rejects different current original binding copy",v=>{v.officialEvidence.config.inheritedOfficial.sourceCommit='f'.repeat(40);});
rejectReceipt("rejects different current original binding copy",v=>{v.officialEvidence.config.inheritedOfficial.sourceCommit='f'.repeat(40);});
rejectInput("rejects missing original bundle",v=>{delete v.officialEvidence;});
rejectReceipt("rejects missing original bundle",v=>{delete v.officialEvidence;});
rejectInput("rejects wrong replay input schema",v=>{v.config.schema='wrong';});
rejectInput("rejects role helper scope as replay input",v=>{v.config.executionScope='role';});
rejectInput("rejects input control drift",v=>{v.observed.controlHashes.launcher='f'.repeat(64);});
rejectReceipt("rejects missing replay receipt",v=>{delete v.config.officialReadReplay.files.receipt;});
rejectReceipt("rejects mismatched observed replay receipt",v=>{v.observed.hashes.receipt='f'.repeat(64);});
rejectReceipt("rejects noncanonical replay receipt",v=>{v.config.officialReadReplay.files.receipt.path='/replay/../outside.json';});
rejectReceipt("rejects missing replay stageTerminal",v=>{delete v.config.officialReadReplay.files.stageTerminal;});
rejectReceipt("rejects mismatched observed replay stageTerminal",v=>{v.observed.hashes.stageTerminal='f'.repeat(64);});
rejectReceipt("rejects noncanonical replay stageTerminal",v=>{v.config.officialReadReplay.files.stageTerminal.path='/replay/../outside.json';});
rejectReceipt("rejects missing replay supervisorTerminal",v=>{delete v.config.officialReadReplay.files.supervisorTerminal;});
rejectReceipt("rejects mismatched observed replay supervisorTerminal",v=>{v.observed.hashes.supervisorTerminal='f'.repeat(64);});
rejectReceipt("rejects noncanonical replay supervisorTerminal",v=>{v.config.officialReadReplay.files.supervisorTerminal.path='/replay/../outside.json';});
rejectReceipt("rejects missing replay outerTerminal",v=>{delete v.config.officialReadReplay.files.outerTerminal;});
rejectReceipt("rejects mismatched observed replay outerTerminal",v=>{v.observed.hashes.outerTerminal='f'.repeat(64);});
rejectReceipt("rejects noncanonical replay outerTerminal",v=>{v.config.officialReadReplay.files.outerTerminal.path='/replay/../outside.json';});
rejectReceipt("rejects missing replay configuration",v=>{delete v.config.officialReadReplay.files.configuration;});
rejectReceipt("rejects mismatched observed replay configuration",v=>{v.observed.hashes.configuration='f'.repeat(64);});
rejectReceipt("rejects noncanonical replay configuration",v=>{v.config.officialReadReplay.files.configuration.path='/replay/../outside.json';});
rejectReceipt("rejects missing replay sourceManifest",v=>{delete v.config.officialReadReplay.files.sourceManifest;});
rejectReceipt("rejects mismatched observed replay sourceManifest",v=>{v.observed.hashes.sourceManifest='f'.repeat(64);});
rejectReceipt("rejects noncanonical replay sourceManifest",v=>{v.config.officialReadReplay.files.sourceManifest.path='/replay/../outside.json';});
rejectReceipt("rejects projected receipt publicationProjection",v=>{v.receipt.publicationProjection=false;});
rejectReceipt("rejects projected receipt originalRawReceiptSha256",v=>{v.receipt.originalRawReceiptSha256=false;});
rejectReceipt("rejects projected stageTerminal publicationProjection",v=>{v.stageTerminal.publicationProjection=false;});
rejectReceipt("rejects projected stageTerminal originalRawReceiptSha256",v=>{v.stageTerminal.originalRawReceiptSha256=false;});
rejectReceipt("rejects projected supervisorTerminal publicationProjection",v=>{v.supervisorTerminal.publicationProjection=false;});
rejectReceipt("rejects projected supervisorTerminal originalRawReceiptSha256",v=>{v.supervisorTerminal.originalRawReceiptSha256=false;});
rejectReceipt("rejects projected outerTerminal publicationProjection",v=>{v.outerTerminal.publicationProjection=false;});
rejectReceipt("rejects projected outerTerminal originalRawReceiptSha256",v=>{v.outerTerminal.originalRawReceiptSha256=false;});
rejectReceipt("rejects projected replayConfig publicationProjection",v=>{v.replayConfig.publicationProjection=false;});
rejectReceipt("rejects projected replayConfig originalRawReceiptSha256",v=>{v.replayConfig.originalRawReceiptSha256=false;});
rejectReceipt("rejects projected replaySourceManifest publicationProjection",v=>{v.replaySourceManifest.publicationProjection=false;});
rejectReceipt("rejects projected replaySourceManifest originalRawReceiptSha256",v=>{v.replaySourceManifest.originalRawReceiptSha256=false;});
rejectReceipt("rejects false replay receipt sourceUnchanged",v=>{v.receipt.checks.sourceUnchanged=false;});
rejectReceipt("rejects truthy replay receipt sourceUnchanged",v=>{v.receipt.checks.sourceUnchanged='true';});
rejectReceipt("rejects missing replay receipt sourceUnchanged",v=>{v.receipt.checks.sourceUnchanged=undefined;});
rejectReceipt("rejects divergent stage sourceUnchanged",v=>{v.stageTerminal.checks.sourceUnchanged=false;});
rejectReceipt("rejects false replay receipt configUnchanged",v=>{v.receipt.checks.configUnchanged=false;});
rejectReceipt("rejects truthy replay receipt configUnchanged",v=>{v.receipt.checks.configUnchanged='true';});
rejectReceipt("rejects missing replay receipt configUnchanged",v=>{v.receipt.checks.configUnchanged=undefined;});
rejectReceipt("rejects divergent stage configUnchanged",v=>{v.stageTerminal.checks.configUnchanged=false;});
rejectReceipt("rejects false replay receipt controlsUnchanged",v=>{v.receipt.checks.controlsUnchanged=false;});
rejectReceipt("rejects truthy replay receipt controlsUnchanged",v=>{v.receipt.checks.controlsUnchanged='true';});
rejectReceipt("rejects missing replay receipt controlsUnchanged",v=>{v.receipt.checks.controlsUnchanged=undefined;});
rejectReceipt("rejects divergent stage controlsUnchanged",v=>{v.stageTerminal.checks.controlsUnchanged=false;});
rejectReceipt("rejects false replay receipt originalEvidenceUnchanged",v=>{v.receipt.checks.originalEvidenceUnchanged=false;});
rejectReceipt("rejects truthy replay receipt originalEvidenceUnchanged",v=>{v.receipt.checks.originalEvidenceUnchanged='true';});
rejectReceipt("rejects missing replay receipt originalEvidenceUnchanged",v=>{v.receipt.checks.originalEvidenceUnchanged=undefined;});
rejectReceipt("rejects divergent stage originalEvidenceUnchanged",v=>{v.stageTerminal.checks.originalEvidenceUnchanged=false;});
rejectReceipt("rejects false replay receipt artifactUnchanged",v=>{v.receipt.checks.artifactUnchanged=false;});
rejectReceipt("rejects truthy replay receipt artifactUnchanged",v=>{v.receipt.checks.artifactUnchanged='true';});
rejectReceipt("rejects missing replay receipt artifactUnchanged",v=>{v.receipt.checks.artifactUnchanged=undefined;});
rejectReceipt("rejects divergent stage artifactUnchanged",v=>{v.stageTerminal.checks.artifactUnchanged=false;});
rejectReceipt("rejects false replay receipt closeReopenEqual",v=>{v.receipt.checks.closeReopenEqual=false;});
rejectReceipt("rejects truthy replay receipt closeReopenEqual",v=>{v.receipt.checks.closeReopenEqual='true';});
rejectReceipt("rejects missing replay receipt closeReopenEqual",v=>{v.receipt.checks.closeReopenEqual=undefined;});
rejectReceipt("rejects divergent stage closeReopenEqual",v=>{v.stageTerminal.checks.closeReopenEqual=false;});
rejectReceipt("rejects false replay receipt readOnlyEnforced",v=>{v.receipt.checks.readOnlyEnforced=false;});
rejectReceipt("rejects truthy replay receipt readOnlyEnforced",v=>{v.receipt.checks.readOnlyEnforced='true';});
rejectReceipt("rejects missing replay receipt readOnlyEnforced",v=>{v.receipt.checks.readOnlyEnforced=undefined;});
rejectReceipt("rejects divergent stage readOnlyEnforced",v=>{v.stageTerminal.checks.readOnlyEnforced=false;});
rejectReceipt("rejects wrong replay execution count readOnlyConnections",v=>{v.receipt.executed.readOnlyConnections+=1;});
rejectReceipt("rejects boolean replay execution count readOnlyConnections",v=>{v.receipt.executed.readOnlyConnections=true;});
rejectReceipt("rejects wrong replay execution count readTransactions",v=>{v.receipt.executed.readTransactions+=1;});
rejectReceipt("rejects boolean replay execution count readTransactions",v=>{v.receipt.executed.readTransactions=true;});
rejectReceipt("rejects wrong replay execution count roleContextReads",v=>{v.receipt.executed.roleContextReads+=1;});
rejectReceipt("rejects boolean replay execution count roleContextReads",v=>{v.receipt.executed.roleContextReads=true;});
rejectReceipt("rejects wrong replay execution count strictCurrentStageChecks",v=>{v.receipt.executed.strictCurrentStageChecks+=1;});
rejectReceipt("rejects boolean replay execution count strictCurrentStageChecks",v=>{v.receipt.executed.strictCurrentStageChecks=true;});
rejectReceipt("rejects wrong replay execution count preparedPlanReads",v=>{v.receipt.executed.preparedPlanReads+=1;});
rejectReceipt("rejects boolean replay execution count preparedPlanReads",v=>{v.receipt.executed.preparedPlanReads=true;});
rejectReceipt("rejects wrong replay execution count officialHelperCalls",v=>{v.receipt.executed.officialHelperCalls+=1;});
rejectReceipt("rejects boolean replay execution count officialHelperCalls",v=>{v.receipt.executed.officialHelperCalls=true;});
rejectReceipt("rejects wrong replay execution count officialWrites",v=>{v.receipt.executed.officialWrites+=1;});
rejectReceipt("rejects boolean replay execution count officialWrites",v=>{v.receipt.executed.officialWrites=true;});
rejectReceipt("rejects wrong replay execution count newOfficialApplications",v=>{v.receipt.executed.newOfficialApplications+=1;});
rejectReceipt("rejects boolean replay execution count newOfficialApplications",v=>{v.receipt.executed.newOfficialApplications=true;});
rejectReceipt("rejects wrong replay execution count newWorkloadActivities",v=>{v.receipt.executed.newWorkloadActivities+=1;});
rejectReceipt("rejects boolean replay execution count newWorkloadActivities",v=>{v.receipt.executed.newWorkloadActivities=true;});
rejectReceipt("rejects wrong replay execution count newPhysicalPitchActions",v=>{v.receipt.executed.newPhysicalPitchActions+=1;});
rejectReceipt("rejects boolean replay execution count newPhysicalPitchActions",v=>{v.receipt.executed.newPhysicalPitchActions=true;});
rejectReceipt("rejects inherited helper recounted as current officialCompleted",v=>{v.stageTerminal.counts.officialCompleted=1;});
rejectReceipt("rejects inherited helper recounted as current roleCompleted",v=>{v.stageTerminal.counts.roleCompleted=1;});
rejectReceipt("rejects inherited helper recounted as current nextCompleted",v=>{v.stageTerminal.counts.nextCompleted=1;});
rejectReceipt("rejects pass0 missing readOnly",v=>{v.receipt.passes[0].readOnly=false;});
rejectReceipt("rejects pass0 missing queryOnly",v=>{v.receipt.passes[0].queryOnly=false;});
rejectReceipt("rejects pass0 missing transactionOwned",v=>{v.receipt.passes[0].transactionOwned=false;});
rejectReceipt("rejects pass0 missing transactionClosed",v=>{v.receipt.passes[0].transactionClosed=false;});
rejectReceipt("rejects pass0 missing connectionClosed",v=>{v.receipt.passes[0].connectionClosed=false;});
rejectReceipt("rejects pass0 nonzero totalChanges",v=>{v.receipt.passes[0].totalChanges=1;});
rejectReceipt("rejects pass0 nonzero walBytesBefore",v=>{v.receipt.passes[0].walBytesBefore=1;});
rejectReceipt("rejects pass0 nonzero walBytesAfter",v=>{v.receipt.passes[0].walBytesAfter=1;});
rejectReceipt("rejects pass0 input byte drift",v=>{v.receipt.passes[0].artifactSha256Before='f'.repeat(64);});
rejectReceipt("rejects pass0 output byte drift",v=>{v.receipt.passes[0].artifactSha256After='f'.repeat(64);});
rejectReceipt("rejects pass0 forged observation digest",v=>{v.receipt.passes[0].observationSha256='f'.repeat(64);});
rejectReceipt("rejects pass1 missing readOnly",v=>{v.receipt.passes[1].readOnly=false;});
rejectReceipt("rejects pass1 missing queryOnly",v=>{v.receipt.passes[1].queryOnly=false;});
rejectReceipt("rejects pass1 missing transactionOwned",v=>{v.receipt.passes[1].transactionOwned=false;});
rejectReceipt("rejects pass1 missing transactionClosed",v=>{v.receipt.passes[1].transactionClosed=false;});
rejectReceipt("rejects pass1 missing connectionClosed",v=>{v.receipt.passes[1].connectionClosed=false;});
rejectReceipt("rejects pass1 nonzero totalChanges",v=>{v.receipt.passes[1].totalChanges=1;});
rejectReceipt("rejects pass1 nonzero walBytesBefore",v=>{v.receipt.passes[1].walBytesBefore=1;});
rejectReceipt("rejects pass1 nonzero walBytesAfter",v=>{v.receipt.passes[1].walBytesAfter=1;});
rejectReceipt("rejects pass1 input byte drift",v=>{v.receipt.passes[1].artifactSha256Before='f'.repeat(64);});
rejectReceipt("rejects pass1 output byte drift",v=>{v.receipt.passes[1].artifactSha256After='f'.repeat(64);});
rejectReceipt("rejects pass1 forged observation digest",v=>{v.receipt.passes[1].observationSha256='f'.repeat(64);});
rejectReceipt("rejects repinned observation closureSourceId",v=>{for(const pass of v.receipt.passes) pass.observation.closureSourceId='foreign'; repinPasses(v);});
rejectReceipt("rejects repinned observation applicationId",v=>{for(const pass of v.receipt.passes) pass.observation.applicationId='foreign'; repinPasses(v);});
rejectReceipt("rejects repinned observation closureStatus",v=>{for(const pass of v.receipt.passes) pass.observation.closureStatus='foreign'; repinPasses(v);});
rejectReceipt("rejects repinned observation closureProposalHash",v=>{for(const pass of v.receipt.passes) pass.observation.closureProposalHash='foreign'; repinPasses(v);});
rejectReceipt("rejects repinned false officialApplied",v=>{for(const pass of v.receipt.passes) pass.observation.officialApplied=false; repinPasses(v);});
rejectReceipt("rejects repinned truthy officialApplied",v=>{for(const pass of v.receipt.passes) pass.observation.officialApplied='true'; repinPasses(v);});
rejectReceipt("rejects repinned missing officialApplied",v=>{for(const pass of v.receipt.passes) pass.observation.officialApplied=undefined; repinPasses(v);});
rejectReceipt("rejects repinned false currentMatchExact",v=>{for(const pass of v.receipt.passes) pass.observation.currentMatchExact=false; repinPasses(v);});
rejectReceipt("rejects repinned truthy currentMatchExact",v=>{for(const pass of v.receipt.passes) pass.observation.currentMatchExact='true'; repinPasses(v);});
rejectReceipt("rejects repinned missing currentMatchExact",v=>{for(const pass of v.receipt.passes) pass.observation.currentMatchExact=undefined; repinPasses(v);});
rejectReceipt("rejects repinned false currentHeadsAuthenticated",v=>{for(const pass of v.receipt.passes) pass.observation.currentHeadsAuthenticated=false; repinPasses(v);});
rejectReceipt("rejects repinned truthy currentHeadsAuthenticated",v=>{for(const pass of v.receipt.passes) pass.observation.currentHeadsAuthenticated='true'; repinPasses(v);});
rejectReceipt("rejects repinned missing currentHeadsAuthenticated",v=>{for(const pass of v.receipt.passes) pass.observation.currentHeadsAuthenticated=undefined; repinPasses(v);});
rejectReceipt("rejects repinned different census applications",v=>{for(const pass of v.receipt.passes) pass.observation.artifact.rowCounts.applications+=1; repinPasses(v);});
rejectReceipt("rejects repinned different census physical_pitch_progress_actions",v=>{for(const pass of v.receipt.passes) pass.observation.artifact.rowCounts.physical_pitch_progress_actions+=1; repinPasses(v);});
rejectReceipt("rejects repinned different census actual_first_base_play_ends",v=>{for(const pass of v.receipt.passes) pass.observation.artifact.rowCounts.actual_first_base_play_ends+=1; repinPasses(v);});
rejectReceipt("rejects repinned different census actual_live_play_fences",v=>{for(const pass of v.receipt.passes) pass.observation.artifact.rowCounts.actual_live_play_fences+=1; repinPasses(v);});
rejectReceipt("rejects repinned different census world_player_workload_activities",v=>{for(const pass of v.receipt.passes) pass.observation.artifact.rowCounts.world_player_workload_activities+=1; repinPasses(v);});
rejectReceipt("rejects repinned different census actual_role_workload_assessments",v=>{for(const pass of v.receipt.passes) pass.observation.artifact.rowCounts.actual_role_workload_assessments+=1; repinPasses(v);});
rejectReceipt("rejects repinned different census actual_role_workload_settlements",v=>{for(const pass of v.receipt.passes) pass.observation.artifact.rowCounts.actual_role_workload_settlements+=1; repinPasses(v);});
rejectReceipt("rejects repinned advanced Match revision",v=>{for(const pass of v.receipt.passes){const o=pass.observation;o.officialReceipt.durableRevision+=1;} repinPasses(v);});
rejectReceipt("rejects repinned foreign current official result",v=>{for(const pass of v.receipt.passes){const o=pass.observation;o.officialReceipt.applicationId='foreign';} repinPasses(v);});
rejectReceipt("rejects repinned different scoring",v=>{for(const pass of v.receipt.passes){const o=pass.observation;o.scoring.kind='complete';} repinPasses(v);});
rejectReceipt("rejects repinned complete workload",v=>{for(const pass of v.receipt.passes){const o=pass.observation;o.workload.kind='complete';} repinPasses(v);});
rejectReceipt("rejects repinned missing retired controller",v=>{for(const pass of v.receipt.passes){const o=pass.observation;o.retiredControllerCount=9;} repinPasses(v);});
rejectReceipt("rejects repinned foreign physical reference",v=>{for(const pass of v.receipt.passes){const o=pass.observation;o.physicalEndReference.snapshotHash='f'.repeat(64);} repinPasses(v);});
rejectReceipt("rejects repinned foreign whole history",v=>{for(const pass of v.receipt.passes){const o=pass.observation;o.wholeHistoryReference.hash='f'.repeat(64);} repinPasses(v);});
rejectReceipt("rejects repinned duplicate participant",v=>{for(const pass of v.receipt.passes){const o=pass.observation;o.participantReferences[1]=clone(o.participantReferences[0]);} repinPasses(v);});
rejectReceipt("rejects repinned missing participant",v=>{for(const pass of v.receipt.passes){const o=pass.observation;o.participantReferences.pop();} repinPasses(v);});
rejectReceipt("rejects repinned changed participant order",v=>{for(const pass of v.receipt.passes){const o=pass.observation;o.participantReferences.reverse();} repinPasses(v);});
rejectReceipt("rejects repinned foreign participant scope",v=>{for(const pass of v.receipt.passes){const o=pass.observation;o.participantReferences[1].careerId='foreign';} repinPasses(v);});
rejectReceipt("rejects repinned duplicate Person",v=>{for(const pass of v.receipt.passes){const o=pass.observation;o.participantReferences[1].personId=o.participantReferences[0].personId;} repinPasses(v);});
rejectReceipt("rejects repinned unknown missing baseline",v=>{for(const pass of v.receipt.passes){const o=pass.observation;o.preparedPlan.missingBaselines.push('foreign');} repinPasses(v);});
rejectReceipt("rejects repinned duplicate missing baseline",v=>{for(const pass of v.receipt.passes){const o=pass.observation;o.preparedPlan.missingBaselines.push(o.preparedPlan.missingBaselines[0]);} repinPasses(v);});
rejectReceipt("rejects repinned not pending plan",v=>{for(const pass of v.receipt.passes){const o=pass.observation;o.preparedPlan.kind='frozen';} repinPasses(v);});
rejectReceipt("rejects repinned missing required assessment",v=>{for(const pass of v.receipt.passes){const o=pass.observation;o.preparedPlan.missingAssessments.pop();} repinPasses(v);});
rejectReceipt("rejects repinned reordered missing assessments",v=>{for(const pass of v.receipt.passes){const o=pass.observation;o.preparedPlan.missingAssessments.reverse();} repinPasses(v);});
rejectReceipt("rejects repinned nonempty workload-kind census",v=>{for(const pass of v.receipt.passes){const o=pass.observation;o.artifact.workloadActivityKinds=[{kind:'MATCH',n:1}];} repinPasses(v);});
rejectReceipt("rejects different authenticated second pass",v=>{v.receipt.passes[1].observation.preparedPlan.missingBaselines=[]; repinPasses(v);});
rejectReceipt("rejects reused connection identity",v=>{v.receipt.passes[1].connectionId=v.receipt.passes[0].connectionId;});
rejectReceipt("rejects one pass instead of close/reopen",v=>{v.receipt.passes.pop();});
rejectReceipt("rejects extra pass instead of exact read scope",v=>{v.receipt.passes.push(clone(v.receipt.passes[1]));});
rejectReceipt("rejects malformed negative pass time",v=>{v.receipt.passes[0].seconds=-1;});
rejectReceipt("rejects old faults labeled newly executed",v=>{v.receipt.newlyExecutedOfficialFaults=['adjudicationDependencyAfterInsert','officialApplicationAfterInsert'];});
rejectReceipt("rejects open artifact handle",v=>{v.receipt.openSqliteHandles=[{fd:9}];});
rejectReceipt("rejects stage open artifact handle",v=>{v.stageTerminal.openSqliteHandles=[{fd:9}];});
rejectReceipt("rejects replay boundary outerTerminal.passed",v=>{set(v,'outerTerminal.passed',false);});
rejectReceipt("rejects replay boundary outerTerminal.supervisorReaped",v=>{set(v,'outerTerminal.supervisorReaped',false);});
rejectReceipt("rejects replay boundary outerTerminal.supervisorExitCode",v=>{set(v,'outerTerminal.supervisorExitCode',1);});
rejectReceipt("rejects replay boundary outerTerminal.outerGuard",v=>{set(v,'outerTerminal.outerGuard','wall');});
rejectReceipt("rejects replay boundary outerTerminal.error",v=>{set(v,'outerTerminal.error','handoff absent');});
rejectReceipt("rejects replay boundary outerTerminal.remainingSupervisorGroup",v=>{set(v,'outerTerminal.remainingSupervisorGroup',[99]);});
rejectReceipt("rejects replay boundary outerTerminal.remainingExecutionGroup",v=>{set(v,'outerTerminal.remainingExecutionGroup',[99]);});
rejectReceipt("rejects replay boundary supervisorTerminal.exitCode",v=>{set(v,'supervisorTerminal.exitCode',1);});
rejectReceipt("rejects replay boundary supervisorTerminal.guard",v=>{set(v,'supervisorTerminal.guard','wall');});
rejectReceipt("rejects replay boundary supervisorTerminal.executingProcessReceiptValid",v=>{set(v,'supervisorTerminal.executingProcessReceiptValid',false);});
rejectReceipt("rejects replay boundary supervisorTerminal.sourceInputAndReceiptAudit.passed",v=>{set(v,'supervisorTerminal.sourceInputAndReceiptAudit.passed',false);});
rejectReceipt("rejects replay boundary supervisorTerminal.remainingOwnedProcesses",v=>{set(v,'supervisorTerminal.remainingOwnedProcesses',[99]);});
rejectReceipt("rejects replay boundary stageTerminal.wholePipelinePassed",v=>{set(v,'stageTerminal.wholePipelinePassed',true);});
rejectReceipt("rejects replay boundary outerTerminal.wholePipelinePassed",v=>{set(v,'outerTerminal.wholePipelinePassed',true);});
rejectReceipt("rejects replay boundary supervisorTerminal.wholePipelinePassed",v=>{set(v,'supervisorTerminal.wholePipelinePassed',true);});
rejectReceipt("rejects replay identity drift receipt.inheritedSourceIdentity.sourceCommit",v=>{set(v,'receipt.inheritedSourceIdentity.sourceCommit','f'.repeat(40));});
rejectReceipt("rejects replay identity drift receipt.sourceIdentity.sourceCommit",v=>{set(v,'receipt.sourceIdentity.sourceCommit','f'.repeat(40));});
rejectReceipt("rejects replay identity drift receipt.originalOfficialReceipt.sha256",v=>{set(v,'receipt.originalOfficialReceipt.sha256','f'.repeat(64));});
rejectReceipt("rejects replay identity drift receipt.inheritedFaultReceipt.sha256",v=>{set(v,'receipt.inheritedFaultReceipt.sha256','f'.repeat(64));});
rejectReceipt("rejects replay identity drift outerTerminal.configSha256",v=>{set(v,'outerTerminal.configSha256','f'.repeat(64));});
rejectReceipt("rejects replay identity drift outerTerminal.references.receipt.sha256",v=>{set(v,'outerTerminal.references.receipt.sha256','f'.repeat(64));});
rejectReceipt("rejects replay identity drift outerTerminal.references.stageTerminal.sha256",v=>{set(v,'outerTerminal.references.stageTerminal.sha256','f'.repeat(64));});
rejectReceipt("rejects replay identity drift outerTerminal.references.supervisorTerminal.sha256",v=>{set(v,'outerTerminal.references.supervisorTerminal.sha256','f'.repeat(64));});
rejectReceipt("rejects replay control drift observed.controlHashes.launcher",v=>{set(v,'observed.controlHashes.launcher','f'.repeat(64));});
rejectReceipt("rejects replay control drift supervisorTerminal.controlHashes.runtimeProbe",v=>{set(v,'supervisorTerminal.controlHashes.runtimeProbe','f'.repeat(64));});
rejectReceipt("rejects replay control drift supervisorTerminal.runtime.nodeSha256",v=>{set(v,'supervisorTerminal.runtime.nodeSha256','f'.repeat(64));});
rejectReceipt("rejects replay actual heap mismatch",v=>{v.supervisorTerminal.runtime.heapLimitMiB=288;});
rejectReceipt("rejects replay wall overrun",v=>{v.supervisorTerminal.runtime.elapsedSeconds=1801;});
rejectReceipt("rejects replay RSS overrun",v=>{v.supervisorTerminal.runtime.peakRssKiB=1536*1024+1;});
rejectReceipt("rejects supervisor receipt list drift",v=>{v.supervisorTerminal.sourceInputAndReceiptAudit.preservedPhaseReceipts=[];});
rejectReceipt("rejects stage receipt list drift",v=>{v.stageTerminal.phaseReceipts=[];});
rejectReceipt("rejects stage original receipt missing",v=>{v.stageTerminal.inheritedStageReceipts=[];});
rejectReceipt("rejects replay Source bytes unverified",v=>{v.observed.replaySourceFilesUnchanged=false;});
rejectReceipt("rejects current artifact bytes drift",v=>{v.observed.artifactSha256='f'.repeat(64);});
rejectReceipt("rejects current artifact WAL",v=>{v.observed.artifactWalBytes=1;});
rejectReceipt("rejects current continuation production drift from replay",v=>{v.replaySourceManifest.files.find(row=>row.path==='src/owner.ts').sha256='f'.repeat(64);});
