import { asRuleProfileId } from '../../core/model/RuleProfileRef';
import { createCanonicalPlateAppearanceTimeline } from '../../core/sim/plateAppearance/CanonicalPlateAppearanceTimeline';
import { resolveAndRecordPitchAgainstBatter } from '../../core/sim/pitching/PitchAgainstBatter';
import { derivePhysicalNonLiveClosure } from '../../core/adjudication/PhysicalNonLiveClosure';
import { deriveOfficialPendingNonLiveResult } from '../OfficialPendingPostPlay';
import { deriveFoulTerminalAcknowledgedResult } from './FoulTerminalAcknowledgementResult';
import { actorJson as json,actorHash as hash } from './PhysicalPlateAppearanceActorEvidenceFromSqlite';
import { activateNextNonLivePlateAppearance } from '../../core/adjudication/NonLiveOfficialApplication';
import { prepareBetweenPlayWorld } from '../../core/adjudication/BetweenPlayWorldReset';
import { resolveOfficialGameBoundary } from '../../core/world/competition/OfficialGameCompletion';
import type { FoulTerminalApplicationProposal } from './ActualFoulTerminalApplication';
import type { CanonicalMatchState } from '../../core/model/CanonicalMatchState';
// STRUCTURAL ONLY: generated Core K timeline and skeletal proposal/effect hashes.
// No successful Native original reader, physical artifact, or accepted input is claimed.
export const boundaryFixture=(kind:'half_change_continuing'|'game_final'='half_change_continuing',overrides:Partial<CanonicalMatchState>={},revision=0)=>{
 const match:CanonicalMatchState={ruleProfileId:asRuleProfileId('structural-boundary'),inning:1,half:kind==='game_final'?'bottom':'top',outs:2,balls:0,strikes:0,bases:{first:null,second:null,third:null},score:{away:0,home:0},playId:7,...overrides};
 let timeline=createCanonicalPlateAppearanceTimeline(match,0);
 for(let i=0;i<3;i++){const tick=timeline.lastEventTick+1;timeline=resolveAndRecordPitchAgainstBatter(timeline,{action:{kind:'take'},trajectory:{start:{tick,position:{x:0,y:1.5,z:18},velocity:{x:0,y:0,z:-30},spin:{x:0,y:100,z:0}},acceleration:{x:0,y:0,z:0},endTick:tick+700000,ticksPerSecond:1000000},plateZ:0,strikeZone:{centerX:0,halfWidth:.2,lowerY:1.4,upperY:1.6},ballRadiusMeters:.0366}).timeline;}
 const clock={originTick:0,ticksPerSecond:1000000,openingTick:0,openingElapsedSeconds:0,ruleTick:timeline.lastEventTick+1,closureTick:timeline.lastEventTick+2};
 const derived=derivePhysicalNonLiveClosure({match,timeline,batterRunnerId:null,gameDay:1,effortPolicy:{policyId:'structural',version:'v1',availableAtDay:1,effortUnitsPerPhysicalPitch:2},snapshotId:'snapshot',ruleTick:clock.ruleTick,closureId:'terminal',closureTick:clock.closureTick});
 const game={seasonId:'season',homeClubId:'home',awayClubId:'away',policy:{version:'structural',minimumInnings:1,maximumInnings:1,tiesAllowed:true},venueBinding:{gameId:'game',venueId:'venue',fixtureEventId:'fixture',fixtureRevision:0}};
 const physicalEndReference={owner:'actual_foul_play_ends',sourceId:'end',sourceVersion:'v1',sourceHash:'a'.repeat(64),snapshotHash:'b'.repeat(64)};
 const terminalSource={sourceId:'terminal',sourceVersion:'v1',capability:'actual_foul_terminal_non_live_application_v1',physicalEndReference,officialReference:{sessionSourceId:'session',revision:1,headSourceId:'head',headHash:'a'.repeat(64)},applicationId:'apply',legalGamePolicy:game.policy};
 const participants=Array.from({length:10},(_,i)=>({binding:{playerId:'outgoing-'+i,personId:'person-'+i,clubId:i?'home':'away'},person:{personId:'person-'+i},role:i?'defender':'batter'}));
 const body={mode:'non_live_pending_post_play_v1',kind:'non_live',matchId:'game',applicationId:'apply',expectedDurableRevision:revision,match,timeline,adjudication:derived.adjudication,context:derived.context,game};
 const p={kind:'terminal_non_live_projected',officialApplied:false,physicalPitchSourceId:'pitch',firstPhysicalPitchSourceId:'pitch',runtimeSourceId:'runtime',scopeId:'scope',callIntent:{sourceId:'intent'},source:terminalSource,gameId:'game',playId:7,originalOfficialRevision:revision,applicationBody:body,nextMatch:derived.nextMatch,clock,physicalEndReference,participants,
 officialObligation:{status:'pending',consumer:null,pendingReason:'terminal_official_closure_unowned',obligationKey:'obligation',scope:{gameId:'game',playId:7}},originalSuccessorKey:'successor',consumptionReference:{owner:'count',sourceId:'count',sourceHash:'a'.repeat(64),snapshotHash:'b'.repeat(64)},officialReference:terminalSource.officialReference} as unknown as FoulTerminalApplicationProposal;
 const official=deriveOfficialPendingNonLiveResult({...p.applicationBody,origin:{owner:'actual_foul_terminal_applications',sourceId:'terminal',sourceVersion:'v1',sourceHash:hash(p.source),snapshotHash:hash(p)}},revision+1),original=deriveFoulTerminalAcknowledgedResult(p,official);
 const reference={owner:'actual_foul_terminal_applications',sourceId:'terminal',sourceVersion:'v1',sourceHash:hash(p.source),proposalHash:hash(p)};
 const setup={baseCenters:{first:{x:1,z:1},second:{x:0,z:2},third:{x:-1,z:1}},defenders:(['P','C','1B','2B','3B','SS','LF','CF','RF']as const).map((registeredPosition,i)=>({playerId:'incoming-'+i,registeredPosition,position:{x:i,z:i}})),activePreviousPlayControllerIds:[]};
 const atTick=clock.closureTick+1,source={sourceId:'boundary',sourceVersion:'v2',capability:'actual_foul_terminal_post_play_setup_v2',terminalReference:reference,controllerReset:'rule_system_retire_original_play',kind,...(kind==='game_final'?{completedAtTick:atTick}:{nextStartedAtTick:atTick,worldSetup:setup})};
 const command={kind:'field',owner:'batted_world_field_actions',sourceId:'field',sourceVersion:'v1',sourceHash:'a'.repeat(64),adoptionSourceId:'field',adoptionSourceHash:'b'.repeat(64),adoptedAt:{originTick:0,elapsedSeconds:0,tick:0},executedThrough:{originTick:0,elapsedSeconds:0,tick:0},acceptedThroughTick:atTick};
 const retirement={version:kind==='game_final'?'actual_foul_terminal_controller_retirement_v2':'actual_foul_terminal_controller_retirement_v1',kind:'rule_system_retire_original_play',sourceId:'boundary',previousPlayId:7,...(kind==='game_final'?{}:{nextPlayId:8}),atTick,physicalEndReference,retired:participants.map(a=>({playerId:a.binding.playerId,personId:a.person.personId,activeCommand:command,ownedMotionCoverage:null})),retainedOriginalFutureWork:{controllers:[]}};
 const payload:any={version:'actual_foul_terminal_post_play_completion_v2',kind,completionId:json(['actual_foul_terminal_post_play_completion_v2','terminal','boundary']),source,sourceHash:hash(source),terminalReference:reference,
 officialReference:{applicationId:'apply',receiptHash:hash(official.receipt),pendingPostPlayHash:hash(official.pendingPostPlay),acknowledgementHash:hash(original.acknowledgement)},scoringReference:{scoringApplicationId:json(['actual_foul_terminal_scoring_v1','terminal']),rowHash:'a'.repeat(64)},
 workloadReference:{terminalSourceId:'terminal',planHash:'b'.repeat(64),participantEffects:participants.map(a=>({playerId:a.binding.playerId,activitySourceId:'activity-'+a.binding.playerId,beforeRevision:0,afterRevision:1,activityHash:'a'.repeat(64),afterHash:'b'.repeat(64)}))},controllerRetirement:retirement};
 if(kind==='game_final'){const boundary=resolveOfficialGameBoundary({...game,gameId:'game',priorMatch:match,application:official.receipt,lineScore:{innings:[{inning:1,awayRuns:match.score.away,homeRuns:match.half==='top'?null:match.score.home}],totals:{away:{runs:match.score.away,hits:0,errors:0},home:{runs:match.score.home,hits:0,errors:0}}}});if(boundary.kind!=='GAME_FINAL')throw new Error('structural final missing');payload.finalResult=boundary.result;payload.scoringHistoryReference={throughDurableRevision:0,earlier:[]};}
 else{payload.activation=activateNextNonLivePlateAppearance({match,timeline,adjudication:derived.adjudication,context:derived.context,application:official.receipt,nextStartedAtTick:atTick});payload.nextWorld=prepareBetweenPlayWorld(payload.activation.nextMatchState,atTick,setup);payload.incomingDefenders=setup.defenders.map(a=>({playerId:a.playerId,personId:'person-'+a.playerId,bindingHash:'a'.repeat(64),workloadRevision:0,workloadHash:'b'.repeat(64)}));}
 return {proposal:p,original,completion:{...payload,snapshotHash:hash(payload)}};
};
