/** TEST ONLY. One separately released motor from a closed genuine decision.
 * The Native owner authenticates its original model/self and the received ancestry. */
import {createRequire} from 'node:module';
import {copyFileSync,existsSync,mkdirSync,readFileSync,statSync,writeFileSync,openSync,fsyncSync,closeSync,constants} from 'node:fs';
import {join} from 'node:path';
import {expect,it} from 'vitest';
import {openSqliteActualReceivedUmpireRenewalMotorStore} from './SqliteActualReceivedUmpireRenewalMotorStore';
import {beginActualLivePlayWrite} from './ActualLivePlayFence';
import {receivedDefenderClaims,receivedRenewalClaims,receivedUnionClaims} from './ActualReceivedUmpireDefenderClaims';
import {actorJson as json,actorHash as hash} from './PhysicalPlateAppearanceActorEvidenceFromSqlite';
import {receivedGenuineFile,receivedGenuineSidecars,receivedGenuineCensus,receivedGenuineHash,receivedGenuineSha,
  type ReceivedGenuinePin,type ReceivedGenuineSidecar} from './ActualReceivedUmpireDefenderGenuineStages.test-support';
import type {RenewalMotorSource} from './ActualReceivedUmpireRenewal';
const {DatabaseSync}=createRequire(import.meta.url)('node:sqlite') as typeof import('node:sqlite');
type Db=InstanceType<typeof DatabaseSync>;
type Checkpoint={schema:string;stage:string;database:ReceivedGenuinePin;receipt:ReceivedGenuinePin;terminal:ReceivedGenuinePin;report:ReceivedGenuinePin;
  inspection:ReceivedGenuinePin;progress:ReceivedGenuinePin;input:ReceivedGenuinePin;config:ReceivedGenuinePin;predecessor:ReceivedGenuinePin;sidecars:readonly ReceivedGenuineSidecar[]};
type Input={schema:'received_renewal_genuine_motor_input_v1';released:boolean;reviewedHead:string;reviewedSrc:string;predecessor:ReceivedGenuinePin};
const inputPath=process.env.RECEIVED_RENEWAL_GENUINE_MOTOR_INPUT;
const readJson=(pin:ReceivedGenuinePin)=>JSON.parse(receivedGenuineFile(pin).toString('utf8'));
const readOnly=<T>(path:string,body:(db:Db)=>T)=>{const db=new DatabaseSync(path,{readOnly:true});try{db.exec('BEGIN');const value=body(db);expect(db.prepare('SELECT total_changes() AS n').get()!.n).toBe(0);db.exec('COMMIT');return value;}finally{if(db.isTransaction)db.exec('ROLLBACK');db.close();}};
const enrollmentTable='actual_received_umpire_renewal_enrollments',decisionTable='actual_received_umpire_renewal_decisions',motorTable='actual_received_umpire_renewal_motors',headTable='actual_received_umpire_renewal_heads',journalTable='actual_received_umpire_renewal_admissions';
it.runIf(!!inputPath)('RNG03 issues the genuine owned renewal motor with three changes and unchanged physical state',()=>{
  const input=JSON.parse(readFileSync(inputPath!,'utf8')) as Input;
  expect(input.schema).toBe('received_renewal_genuine_motor_input_v1');expect(input.released,'separate runtime release required before a genuine copy').toBe(true);
  expect(input.reviewedHead).toBe('45ff861d7b38f6003eb1a41f7884b30838f00539');expect(input.reviewedSrc).toBe('03faee383678b28552f7bdcc4c71c1f975092727');
  expect(input.predecessor.sha256).toBe('b0907bd806ab7c26af87c11a6d42c6709ca55157c49de2afffd6053f59b50f38');
  const checkpoint=readJson(input.predecessor) as Checkpoint,receipt=readJson(checkpoint.receipt),terminal=readJson(checkpoint.terminal),report=readJson(checkpoint.report),inspection=readJson(checkpoint.inspection),config=readJson(checkpoint.config),priorInput=readJson(checkpoint.input);
  expect(checkpoint).toMatchObject({schema:'received_renewal_genuine_checkpoint_v1',stage:'renewal-decision'});
  expect(config.sourceIdentity).toMatchObject({candidateHead:'aca1de075c264bcad639d733cb13ac6c6c10d12e',candidateSrc:'cfe9f7d35b51ba2b2935920634f5a64070485cc5'});
  expect(terminal).toMatchObject({status:'passed',originalChildExit:0,remainingOwnedProcesses:[],failures:[],configSha256:checkpoint.config.sha256,tests:{passedCases:1,expectedFailedCases:0,skipped:[],reportSha256:checkpoint.report.sha256}});
  for(const group of ['source','dependencies','controls','runtime']){expect(terminal.before[group].sha256).toBe(config.inputs[group].sha256);expect(terminal.after[group].sha256).toBe(config.inputs[group].sha256);}
  expect(report).toMatchObject({success:true,numPassedTests:1,numFailedTests:0,numPendingTests:0});
  expect(inspection).toMatchObject({outputDatabaseSha256:checkpoint.database.sha256,receiptSha256:checkpoint.receipt.sha256,terminalSha256:checkpoint.terminal.sha256,inheritedOriginalTablesPreserved:75,inheritedOriginalRowsPreserved:145,enrollmentAndFirstJournalPreserved:true,legacyAdmissionsPreserved:24,newRows:2,exactNativeChanges:3,schemaPreserved:true});
  const progress=receivedGenuineFile(checkpoint.progress).toString('utf8').trim().split('\n').map(line=>JSON.parse(line));
  expect(progress.map(p=>p.phase)).toEqual(['acceptance_start','uncommitted_write_observed','uncommitted_write_observed','uncommitted_write_observed','owner_returned','receipt_closed']);expect(progress[5]).toMatchObject({receiptSha256:checkpoint.receipt.sha256,outputDatabaseSha256:checkpoint.database.sha256,nativeConnectionsClosed:true});
  expect(priorInput.predecessor).toEqual(checkpoint.predecessor);expect(checkpoint.predecessor.sha256).toBe('092f915c21578ea6ba9559d648743aced99aa70e226b68b6b78329d3c867efde');
  const enrollmentCheckpoint=readJson(checkpoint.predecessor) as Checkpoint,enrollmentReceipt=readJson(enrollmentCheckpoint.receipt),enrollment=enrollmentReceipt.accepted;
  expect(enrollmentCheckpoint.stage).toBe('renewal-enrollment');expect(enrollmentCheckpoint.predecessor.sha256).toBe('c7b8eb4021b3a80c7b9c389c63d7f251bfbeffa1fbaae29826a692dc646a7ad7');receivedGenuineFile(enrollmentCheckpoint.predecessor);
  expect(enrollmentReceipt.acceptedHash).toBe(hash(enrollment));expect(enrollmentReceipt.acceptedJson).toBe(json(enrollment));
  expect(receipt).toMatchObject({schema:'received_renewal_genuine_decision_receipt_v1',reviewedHead:input.reviewedHead,reviewedSrc:input.reviewedSrc,outputDatabaseSha256:checkpoint.database.sha256,inheritedOriginalTablesPreserved:75,inheritedOriginalRowsPreserved:145,originalAdmissionsPreserved:24,originalRolesPreserved:50,changes:3,authorityCallbacks:7,newMotorOrAdoption:false,physicalAdvancement:false,pending:'renewal_motor'});
  const decision=receipt.accepted;expect(receipt.acceptedHash).toBe(hash(decision));expect(receipt.acceptedJson).toBe(json(decision));expect(decision.enrollmentHash).toBe(enrollmentReceipt.acceptedHash);
  receivedGenuineSidecars(checkpoint.database,checkpoint.sidecars);
  const directory=join(process.env.TMPDIR!,'artifact');expect(existsSync(directory)).toBe(false);mkdirSync(directory,{mode:0o700});const path=join(directory,'received-renewal.sqlite');
  copyFileSync(checkpoint.database.path,path,constants.COPYFILE_EXCL);receivedGenuineFile({path,sha256:checkpoint.database.sha256});
  const standalone=()=>{for(const suffix of ['-wal','-journal'])expect(existsSync(path+suffix)?statSync(path+suffix).size:0).toBe(0);};
  const before=readOnly(path,receivedGenuineCensus);standalone();expect(receivedGenuineHash(before)).toBe(receipt.afterCensusHash);expect(before.tables).toHaveLength(80);expect(before.tables.reduce((n,t)=>n+t.rows.length,0)).toBe(150);
  const rows=(c:typeof before,t:string)=>c.tables.find(v=>v.name===t)!.rows.map(row=>JSON.parse(row));
  expect(rows(before,enrollmentTable)[0]).toMatchObject({snapshot_json:enrollmentReceipt.acceptedJson,snapshot_hash:enrollmentReceipt.acceptedHash});expect(rows(before,decisionTable)[0]).toMatchObject({snapshot_json:receipt.acceptedJson,snapshot_hash:receipt.acceptedHash});
  const models=rows(before,'world_player_locomotion_models').filter(row=>row.source_id===enrollment.anchor.locomotionModel.sourceId);expect(models).toHaveLength(1);const model=JSON.parse(models[0].snapshot_json);
  expect(hash(model)).toBe(enrollment.anchor.locomotionModel.snapshotHash);expect(hash(model.source)).toBe(enrollment.anchor.locomotionModel.sourceHash);expect(model.source.sourceId).toBe('scheduled-locomotion-model-home-1');
  expect(models[0]).toMatchObject({source_json:json(model.source),source_hash:hash(model.source),snapshot_hash:hash(model)});expect(model.source).toMatchObject({playerId:enrollment.playerId,personLinkSourceId:enrollment.receiver.personLinkSourceId,careerId:enrollment.receiver.careerId,fieldingModelSourceId:enrollment.receiver.fieldingModelSourceId});expect(model.source.acceptedAtDay).toBeLessThanOrEqual(enrollment.receiver.gameDay);expect(hash(model.fieldingModel)).toBe(enrollment.anchor.fieldingModelHash);expect(model.fieldingModel.person).toMatchObject({playerId:enrollment.playerId,personId:enrollment.receiver.personId,sourceId:enrollment.receiver.personLinkSourceId});
  const source:RenewalMotorSource={sourceId:'received-renewal-motor-home-1',sourceVersion:'genuine-received-native-renewal-v1',capability:'received_umpire_renewal_motor_v1',renewalEnrollmentSourceId:enrollment.source.sourceId,renewalDecisionSourceId:decision.source.sourceId};
  let progressSequence=0;
  const checkpointProgress=(phase:string,details:Record<string,unknown>={})=>{const fd=openSync(join(directory,'renewal-motor-progress.jsonl'),progressSequence===0?'ax':'a',0o600);
    try{writeFileSync(fd,JSON.stringify({schema:'received_renewal_motor_progress_v1',sequence:++progressSequence,phase,wallTimeUnixMilliseconds:Date.now(),...details})+'\n');fsyncSync(fd);}finally{closeSync(fd);}
    const d=openSync(directory,'r');try{fsyncSync(d);}finally{closeSync(d);}};
  const nativePrepare=DatabaseSync.prototype.prepare,nativeExec=DatabaseSync.prototype.exec,connections=new Map<Db,number>(),writes:{operation:string;table:string;changes:number}[]=[];let callbacks=0;
  const changes=(db:Db)=>Number(nativePrepare.call(db,'SELECT total_changes() AS n').get()!.n),touch=(db:Db)=>{if(!connections.has(db))connections.set(db,changes(db));};
  DatabaseSync.prototype.exec=function(this:Db,sql:string){touch(this);return nativeExec.call(this,sql);};
  DatabaseSync.prototype.prepare=function(this:Db,sql:string){touch(this);const db=this,statement=nativePrepare.call(this,sql),match=/^(INSERT INTO|UPDATE) (actual_received_umpire_renewal_[a-z_]+)/.exec(sql);
    if(match){const run=statement.run.bind(statement);statement.run=((...args:Parameters<typeof statement.run>)=>{const r=run(...args),w={operation:match[1],table:match[2],changes:Number(r.changes)};writes.push(w);checkpointProgress(db.isTransaction?'uncommitted_write_observed':'write_returned_without_transaction',{...w,sourceId:source.sourceId,writeOrdinal:writes.length,isTransaction:db.isTransaction,durability:'not_asserted'});return r;}) as typeof statement.run;}return statement;} as typeof nativePrepare;
  let accepted:ReturnType<ReturnType<typeof openSqliteActualReceivedUmpireRenewalMotorStore>['accept']>;
  try{const owner=openSqliteActualReceivedUmpireRenewalMotorStore(path,{readAcceptedMotor:id=>{callbacks++;expect(id).toBe(source.sourceId);return source;}});
    try{checkpointProgress('acceptance_start',{sourceId:source.sourceId});accepted=owner.accept(source.sourceId);checkpointProgress('owner_returned',{sourceId:source.sourceId,acceptedHash:hash(accepted),databaseClosePending:true});
      expect(connections.size).toBe(1);expect([...connections].map(([db,n])=>changes(db)-n)).toEqual([3]);for(const db of connections.keys()){expect(db.isTransaction).toBe(false);expect(db.prepare('PRAGMA query_only').get()!.query_only).toBe(0);}}
    finally{owner.close();}expect([...connections.keys()].every(db=>!db.isOpen)).toBe(true);
  }finally{DatabaseSync.prototype.prepare=nativePrepare;DatabaseSync.prototype.exec=nativeExec;}
  standalone();expect(callbacks).toBe(7);expect(writes).toEqual([{operation:'INSERT INTO',table:motorTable,changes:1},{operation:'UPDATE',table:headTable,changes:1},{operation:'INSERT INTO',table:journalTable,changes:1}]);
  expect(accepted!.source).toEqual(source);expect(accepted!.enrollmentHash).toBe(enrollmentReceipt.acceptedHash);expect(accepted!.decisionHash).toBe(receipt.acceptedHash);
  expect(accepted!).toMatchObject({gameId:enrollment.gameId,playId:enrollment.playId,physicalPitchSourceId:enrollment.physicalPitchSourceId,playerId:enrollment.playerId,renewalEnrollmentSourceId:enrollment.source.sourceId});
  const motor=accepted!.receipt,self=motor.self,participant=enrollment.anchor.participants.find((p:{playerId:string})=>p.playerId===enrollment.playerId);expect(participant).toBeDefined();expect(hash(self)).toBe(enrollment.anchor.selfHash);expect(hash(self.activeCommand)).toBe(participant.activeCommandHash);expect(hash(self.ownedMotionCoverage!.roleAuthorities)).toBe(participant.roleAuthoritiesHash);
  expect(motor.decisionSourceId).toBe(decision.source.sourceId);expect(motor.intent).toEqual(decision.receipt.selected.intent);expect(motor.target).toEqual(decision.receipt.target);expect({...motor.startAt,ticksPerSecond:motor.ticksPerSecond}).toEqual(enrollment.cut);expect(motor.issuedAt).toEqual(motor.startAt);expect(motor.movementStartTick).toBe(enrollment.cut.tick);
  expect({...self.at,ticksPerSecond:self.ticksPerSecond}).toEqual(enrollment.cut);expect(decision.receipt.cut).toEqual(enrollment.cut);expect(enrollment.cut.elapsedSeconds).toBe((enrollment.cut.tick-enrollment.cut.originTick)/enrollment.cut.ticksPerSecond);expect(motor.segment.ticksPerSecond).toBe(enrollment.cut.ticksPerSecond);
  expect(motor.lifecycle).toEqual({status:'adoption_pending',executedThrough:null});expect(motor.relativeCommandConvention).toBe('retain_declared_role_acceleration_v1');expect(motor.roleAuthorities).toEqual(self.ownedMotionCoverage!.roleAuthorities);
  const roleNames=['body','glove','left_foot','right_foot','tag_hand'];expect(motor.retainedRoles.map(role=>role.role).sort()).toEqual(roleNames);expect(motor.command.primitiveMotions.map(role=>role.role).sort()).toEqual(roleNames);
  for(const role of motor.retainedRoles){const authority=motor.roleAuthorities.find(a=>a.role===role.role)!,physical=self.roles.find(p=>p.role===role.role)!;expect(role.command).toEqual(authority.command);expect(role.acceptedThroughTick).toBe(authority.acceptedThroughTick);expect(role.acceptedThroughTick).toBeGreaterThan(enrollment.cut.tick);expect(role.acceptedThroughTick).toBeLessThanOrEqual(role.command.acceptedThroughTick);expect(role.radiusMeters).toBe(physical.radiusMeters);expect(role.offsetAcceleration).toEqual(physical.declaredPose.relativeAcceleration);expect(motor.command.primitiveMotions.find(p=>p.role===role.role)!.offsetAcceleration).toEqual(role.offsetAcceleration);}
  expect(motor.segment.startPosition).toEqual({x:self.root.position.x,z:self.root.position.z});expect(motor.segment.startVelocity).toEqual({x:self.root.velocity.x,z:self.root.velocity.z});expect(motor.command.playerId).toBe(enrollment.playerId);expect(motor.command.bodyAcceleration).toEqual({x:motor.segment.acceleration.x,y:self.root.acceleration.y,z:motor.segment.acceleration.z});
  expect(motor.segment.startTick).toBe(enrollment.cut.tick);expect(motor.coverageEndTick).toBe(Math.min(enrollment.cut.tick+model.source.calibration.maxIntegrationStepTicks,...motor.roleAuthorities.map(a=>a.acceptedThroughTick)));expect(motor.segment.endTick).toBe(motor.coverageEndTick);expect(motor.coverageEndTick).toBeGreaterThan(motor.segment.startTick);
  const after=readOnly(path,db=>{expect(receivedDefenderClaims(db,enrollment)).toHaveLength(9);expect(receivedRenewalClaims(db,enrollment)).toHaveLength(7);expect(receivedUnionClaims(db,enrollment)).toHaveLength(16);for(const selected of [{gameId:enrollment.gameId,playId:enrollment.playId},{gameId:enrollment.gameId,playId:enrollment.playId,physicalPitchSourceId:enrollment.physicalPitchSourceId}])
    expect(()=>beginActualLivePlayWrite(db,selected,{owner:'batted_world_field_executions',sourceId:'renewal-genuine-blocked-after-motor'})).toThrow(/received.*pending/i);return receivedGenuineCensus(db);});standalone();expect(after.schema).toEqual(before.schema);expect(after.tables).toHaveLength(80);expect(after.tables.reduce((n,t)=>n+t.rows.length,0)).toBe(152);
  for(const table of before.tables.filter(t=>![motorTable,headTable,journalTable].includes(t.name)))expect(after.tables.find(t=>t.name===table.name)).toEqual(table);
  expect(rows(before,motorTable)).toHaveLength(0);expect(rows(after,motorTable)).toHaveLength(1);expect(rows(after,motorTable)[0]).toMatchObject({source_json:json(source),source_hash:hash(source),snapshot_json:json(accepted!),snapshot_hash:hash(accepted!)});
  expect(rows(after,headTable)).toEqual([{...rows(before,headTable)[0],stage:3,owner:motorTable,source_id:source.sourceId,renewal_motor_source_id:source.sourceId}]);expect(rows(after,journalTable)).toHaveLength(3);expect(rows(after,journalTable).slice(0,2)).toEqual(rows(before,journalTable));
  const ownerRow=rows(after,motorTable)[0],scope={game_id:enrollment.gameId,play_id:enrollment.playId,physical_pitch_source_id:enrollment.physicalPitchSourceId,player_id:enrollment.playerId,runtime_source_id:enrollment.runtimeSourceId,received_enrollment_source_id:enrollment.receivedEnrollmentSourceId,origin_process_source_id:enrollment.originProcessSourceId,received_replan_source_id:enrollment.receivedReplanSourceId,renewal_enrollment_source_id:enrollment.source.sourceId};
  expect(ownerRow).toMatchObject({...scope,source_version:source.sourceVersion,renewal_decision_source_id:decision.source.sourceId});const {__rowid,receipt_hash,...journalBody}=rows(after,journalTable)[2];expect(__rowid).toBe(3);expect(receipt_hash).toBe(hash(journalBody));expect(journalBody).toEqual({...scope,sequence:3,owner:motorTable,source_id:source.sourceId,source_version:source.sourceVersion,legacy_prefix_digest:enrollment.anchor.legacyAdmissionPrefix.digest,received_prefix_digest:enrollment.anchor.receivedJournal.digest,source_hash:hash(source),snapshot_hash:hash(accepted!),previous_receipt_hash:rows(before,journalTable)[1].receipt_hash});
  receivedGenuineSidecars(checkpoint.database,checkpoint.sidecars);
  const outputDatabaseSha256=receivedGenuineSha(readFileSync(path)),receiptPath=join(directory,'received-renewal-motor.json'),fd=openSync(receiptPath,'wx',0o600);
  try{writeFileSync(fd,JSON.stringify({schema:'received_renewal_genuine_motor_receipt_v1',reviewedHead:input.reviewedHead,reviewedSrc:input.reviewedSrc,predecessorCheckpoint:input.predecessor,inputDatabaseSha256:checkpoint.database.sha256,outputDatabaseSha256,
    source,accepted:accepted!,acceptedJson:json(accepted!),acceptedHash:hash(accepted!),beforeCensusHash:receivedGenuineHash(before),afterCensusHash:receivedGenuineHash(after),changes:3,authorityCallbacks:callbacks,writes,
    inheritedOriginalTablesPreserved:75,inheritedOriginalRowsPreserved:145,originalAdmissionsPreserved:24,originalRolesPreserved:50,physicalAdvancement:false,newAdoption:false,pending:'renewal_physical_adoption',closureCredit:0},null,2)+'\n');fsyncSync(fd);}finally{closeSync(fd);}
  checkpointProgress('receipt_closed',{sourceId:source.sourceId,receiptSha256:receivedGenuineSha(readFileSync(receiptPath)),outputDatabaseSha256,nativeConnectionsClosed:true});
});
