/** TEST ONLY. One separately released zero-horizon adoption from a closed genuine motor.
 * Archived predecessor data is an oracle only; the Native owner authenticates all execution inputs. */
import {createRequire} from 'node:module';
import {copyFileSync,existsSync,mkdirSync,readFileSync,statSync,writeFileSync,openSync,fsyncSync,closeSync,constants} from 'node:fs';
import {join} from 'node:path';
import {expect,it} from 'vitest';
import {openSqliteActualReceivedUmpireRenewalAdoptionStore} from './SqliteActualReceivedUmpireRenewalAdoptionStore';
import {ownedScheduledMotionArchiveEncoding as encoding} from './OwnedScheduledMotionArchive';
import {samplePiecewiseFieldActor} from '../../core/sim/ball/BattedWorldPiecewiseFieldMotion';
import {beginActualLivePlayWrite} from './ActualLivePlayFence';
import {receivedDefenderClaims,receivedRenewalClaims,receivedUnionClaims} from './ActualReceivedUmpireDefenderClaims';
import {actorJson as json,actorHash as hash} from './PhysicalPlateAppearanceActorEvidenceFromSqlite';
import {receivedGenuineFile,receivedGenuineSidecars,receivedGenuineCensus,receivedGenuineHash,receivedGenuineSha,
  type ReceivedGenuinePin,type ReceivedGenuineSidecar} from './ActualReceivedUmpireDefenderGenuineStages.test-support';
import type {RenewalAdoptionExecutionSource} from './ActualReceivedUmpireRenewal';
const {DatabaseSync}=createRequire(import.meta.url)('node:sqlite') as typeof import('node:sqlite');
type Db=InstanceType<typeof DatabaseSync>;
type Checkpoint={schema:string;stage:string;database:ReceivedGenuinePin;receipt:ReceivedGenuinePin;terminal:ReceivedGenuinePin;report:ReceivedGenuinePin;
  inspection:ReceivedGenuinePin;progress:ReceivedGenuinePin;input:ReceivedGenuinePin;config:ReceivedGenuinePin;predecessor:ReceivedGenuinePin;sidecars:readonly ReceivedGenuineSidecar[]};
type Input={schema:'received_renewal_genuine_adoption_input_v1';released:boolean;reviewedHead:string;reviewedSrc:string;predecessor:ReceivedGenuinePin};
const inputPath=process.env.RECEIVED_RENEWAL_GENUINE_ADOPTION_INPUT;
const readJson=(pin:ReceivedGenuinePin)=>JSON.parse(receivedGenuineFile(pin).toString('utf8'));
const readOnly=<T>(path:string,body:(db:Db)=>T)=>{const db=new DatabaseSync(path,{readOnly:true});try{db.exec('BEGIN');const value=body(db);expect(db.prepare('SELECT total_changes() AS n').get()!.n).toBe(0);db.exec('COMMIT');return value;}finally{if(db.isTransaction)db.exec('ROLLBACK');db.close();}};
const physicalTable='batted_world_field_executions',physicalHeadTable='batted_world_field_execution_heads',headTable='actual_received_umpire_renewal_heads',journalTable='actual_received_umpire_renewal_admissions';
it.runIf(!!inputPath)('RNG04 adopts the genuine renewal motor through four changes at an unchanged physical cut',()=>{
  const input=JSON.parse(readFileSync(inputPath!,'utf8')) as Input;
  expect(input.schema).toBe('received_renewal_genuine_adoption_input_v1');expect(input.released,'separate runtime release required before a genuine copy').toBe(true);
  expect(input.reviewedHead).toBe('45ff861d7b38f6003eb1a41f7884b30838f00539');expect(input.reviewedSrc).toBe('03faee383678b28552f7bdcc4c71c1f975092727');
  expect(input.predecessor.sha256).toBe('78266b154619e13194346ffa687be78d73b93b69b3ba62537ae368cf8be07825');
  const checkpoint=readJson(input.predecessor) as Checkpoint,receipt=readJson(checkpoint.receipt),terminal=readJson(checkpoint.terminal),report=readJson(checkpoint.report),inspection=readJson(checkpoint.inspection),config=readJson(checkpoint.config),priorInput=readJson(checkpoint.input);
  expect(checkpoint).toMatchObject({schema:'received_renewal_genuine_checkpoint_v1',stage:'renewal-motor'});expect(config.sourceIdentity).toMatchObject({candidateHead:'aead4c77ac17eb73a18fa4c0de66a137ef7729cc',candidateSrc:'a1d83e394d90f6520f82bc4ab5baac551fa3a609'});
  expect(terminal).toMatchObject({status:'passed',originalChildExit:0,remainingOwnedProcesses:[],failures:[],configSha256:checkpoint.config.sha256,tests:{passedCases:1,expectedFailedCases:0,skipped:[],reportSha256:checkpoint.report.sha256}});
  for(const group of ['source','dependencies','controls','runtime']){expect(terminal.before[group].sha256).toBe(config.inputs[group].sha256);expect(terminal.after[group].sha256).toBe(config.inputs[group].sha256);}
  expect(report).toMatchObject({success:true,numPassedTests:1,numFailedTests:0,numPendingTests:0});expect(inspection).toMatchObject({outputDatabaseSha256:checkpoint.database.sha256,receiptSha256:checkpoint.receipt.sha256,terminalSha256:checkpoint.terminal.sha256,inheritedOriginalTablesPreserved:75,inheritedOriginalRowsPreserved:145,enrollmentDecisionAndJournalPrefixPreserved:true,legacyAdmissionsPreserved:24,newRows:2,exactNativeChanges:3,schemaPreserved:true});
  const progress=receivedGenuineFile(checkpoint.progress).toString('utf8').trim().split('\n').map(line=>JSON.parse(line));expect(progress.map(p=>p.phase)).toEqual(['acceptance_start','uncommitted_write_observed','uncommitted_write_observed','uncommitted_write_observed','owner_returned','receipt_closed']);expect(progress[5]).toMatchObject({receiptSha256:checkpoint.receipt.sha256,outputDatabaseSha256:checkpoint.database.sha256,nativeConnectionsClosed:true});
  expect(priorInput.predecessor).toEqual(checkpoint.predecessor);expect(checkpoint.predecessor.sha256).toBe('b0907bd806ab7c26af87c11a6d42c6709ca55157c49de2afffd6053f59b50f38');
  const decisionCheckpoint=readJson(checkpoint.predecessor) as Checkpoint,decisionReceipt=readJson(decisionCheckpoint.receipt);expect(decisionCheckpoint.stage).toBe('renewal-decision');expect(decisionCheckpoint.predecessor.sha256).toBe('092f915c21578ea6ba9559d648743aced99aa70e226b68b6b78329d3c867efde');
  const enrollmentCheckpoint=readJson(decisionCheckpoint.predecessor) as Checkpoint,enrollmentReceipt=readJson(enrollmentCheckpoint.receipt),enrollment=enrollmentReceipt.accepted;expect(enrollmentCheckpoint.stage).toBe('renewal-enrollment');expect(enrollmentCheckpoint.predecessor.sha256).toBe('c7b8eb4021b3a80c7b9c389c63d7f251bfbeffa1fbaae29826a692dc646a7ad7');receivedGenuineFile(enrollmentCheckpoint.predecessor);
  expect(receipt).toMatchObject({schema:'received_renewal_genuine_motor_receipt_v1',reviewedHead:input.reviewedHead,reviewedSrc:input.reviewedSrc,outputDatabaseSha256:checkpoint.database.sha256,inheritedOriginalTablesPreserved:75,inheritedOriginalRowsPreserved:145,originalAdmissionsPreserved:24,originalRolesPreserved:50,changes:3,authorityCallbacks:7,newAdoption:false,physicalAdvancement:false,pending:'renewal_physical_adoption'});
  const motor=receipt.accepted;expect(receipt.acceptedHash).toBe(hash(motor));expect(receipt.acceptedJson).toBe(json(motor));expect(motor.enrollmentHash).toBe(enrollmentReceipt.acceptedHash);expect(motor.decisionHash).toBe(decisionReceipt.acceptedHash);expect(enrollmentReceipt.acceptedHash).toBe(hash(enrollment));expect(decisionReceipt.acceptedHash).toBe(hash(decisionReceipt.accepted));
  receivedGenuineSidecars(checkpoint.database,checkpoint.sidecars);const directory=join(process.env.TMPDIR!,'artifact');expect(existsSync(directory)).toBe(false);mkdirSync(directory,{mode:0o700});const path=join(directory,'received-renewal.sqlite');copyFileSync(checkpoint.database.path,path,constants.COPYFILE_EXCL);receivedGenuineFile({path,sha256:checkpoint.database.sha256});
  const standalone=()=>{for(const suffix of ['-wal','-journal'])expect(existsSync(path+suffix)?statSync(path+suffix).size:0).toBe(0);};
  const before=readOnly(path,receivedGenuineCensus);standalone();expect(receivedGenuineHash(before)).toBe(receipt.afterCensusHash);expect(before.tables).toHaveLength(80);expect(before.tables.reduce((n,t)=>n+t.rows.length,0)).toBe(152);
  const rows=(c:typeof before,t:string)=>c.tables.find(v=>v.name===t)!.rows.map(row=>JSON.parse(row));
  const source:RenewalAdoptionExecutionSource={sourceId:'received-renewal-adoption-home-1',sourceVersion:'genuine-received-native-renewal-v1',baseFieldSourceId:enrollment.anchor.baseField.sourceId,previousExecutionSourceId:enrollment.anchor.physicalPredecessor.sourceId,action:{kind:'received_renewal_adoption_v1',renewalEnrollmentSourceId:enrollment.source.sourceId,renewalMotorSourceId:motor.source.sourceId}};
  const predecessors=rows(before,physicalTable).filter(r=>r.source_id===source.previousExecutionSourceId);expect(predecessors).toHaveLength(1);const predecessorRow=predecessors[0],previous=JSON.parse(predecessorRow.snapshot_json),oldField=previous.execution.field;
  expect(predecessorRow).toMatchObject({source_id:'received-input-reception-cut',revision:10,source_hash:enrollment.anchor.physicalPredecessor.sourceHash,snapshot_hash:enrollment.anchor.physicalPredecessor.snapshotHash});expect(receivedGenuineSha(Buffer.from(predecessorRow.snapshot_json))).toBe(predecessorRow.snapshot_hash);expect(previous.snapshotFormat).toBe('owned_scheduled_field_execution_manifest_v1');
  let progressSequence=0;
  const checkpointProgress=(phase:string,details:Record<string,unknown>={})=>{const fd=openSync(join(directory,'renewal-adoption-progress.jsonl'),progressSequence===0?'ax':'a',0o600);try{writeFileSync(fd,JSON.stringify({schema:'received_renewal_adoption_progress_v1',sequence:++progressSequence,phase,wallTimeUnixMilliseconds:Date.now(),...details})+'\n');fsyncSync(fd);}finally{closeSync(fd);}const d=openSync(directory,'r');try{fsyncSync(d);}finally{closeSync(d);}};
  const nativePrepare=DatabaseSync.prototype.prepare,nativeExec=DatabaseSync.prototype.exec,connections=new Map<Db,number>(),writes:{operation:string;table:string;changes:number}[]=[];let callbacks=0;
  const changes=(db:Db)=>Number(nativePrepare.call(db,'SELECT total_changes() AS n').get()!.n),touch=(db:Db)=>{if(!connections.has(db))connections.set(db,changes(db));};DatabaseSync.prototype.exec=function(this:Db,sql:string){touch(this);return nativeExec.call(this,sql);};
  DatabaseSync.prototype.prepare=function(this:Db,sql:string){touch(this);const db=this,statement=nativePrepare.call(this,sql),match=/^(INSERT INTO|UPDATE) (batted_world_field_executions|batted_world_field_execution_heads|actual_received_umpire_renewal_heads|actual_received_umpire_renewal_admissions)(?:\s|$)/.exec(sql);
    if(match){const run=statement.run.bind(statement);statement.run=((...args:Parameters<typeof statement.run>)=>{const r=run(...args),w={operation:match[1],table:match[2],changes:Number(r.changes)};writes.push(w);checkpointProgress(db.isTransaction?'uncommitted_write_observed':'write_returned_without_transaction',{...w,sourceId:source.sourceId,writeOrdinal:writes.length,isTransaction:db.isTransaction,durability:'not_asserted'});return r;}) as typeof statement.run;}return statement;} as typeof nativePrepare;
  let accepted:ReturnType<ReturnType<typeof openSqliteActualReceivedUmpireRenewalAdoptionStore>['accept']>;
  try{const owner=openSqliteActualReceivedUmpireRenewalAdoptionStore(path,{readAcceptedAdoption:id=>{callbacks++;expect(id).toBe(source.sourceId);return source;}});try{checkpointProgress('acceptance_start',{sourceId:source.sourceId});accepted=owner.accept(source.sourceId);checkpointProgress('owner_returned',{sourceId:source.sourceId,acceptedArchiveHash:encoding(accepted).hash,databaseClosePending:true});expect(connections.size).toBe(1);expect([...connections].map(([db,n])=>changes(db)-n)).toEqual([4]);for(const db of connections.keys()){expect(db.isTransaction).toBe(false);expect(db.prepare('PRAGMA query_only').get()!.query_only).toBe(0);}}finally{owner.close();}expect([...connections.keys()].every(db=>!db.isOpen)).toBe(true);}finally{DatabaseSync.prototype.prepare=nativePrepare;DatabaseSync.prototype.exec=nativeExec;}
  standalone();expect(callbacks).toBe(10);expect(writes).toEqual([{operation:'INSERT INTO',table:physicalTable,changes:1},{operation:'UPDATE',table:physicalHeadTable,changes:1},{operation:'UPDATE',table:headTable,changes:1},{operation:'INSERT INTO',table:journalTable,changes:1}]);
  expect(accepted!.source).toEqual(source);expect(accepted!.revision).toBe(11);expect(accepted!.execution.kind).toBe('received_renewal_adoption_v1');if(accepted!.execution.kind!=='received_renewal_adoption_v1')throw new Error('genuine received adoption kind differs');
  const result=accepted!.execution,composition=result.composition,cut=enrollment.cut,at={originTick:cut.originTick,elapsedSeconds:cut.elapsedSeconds,tick:cut.tick},archive=encoding(accepted!),manifest=JSON.parse(archive.json);
  expect(manifest.snapshotFormat).toBe('received_renewal_adoption_snapshot_v1');expect(manifest.baseField).toMatchObject({sourceHash:enrollment.anchor.baseField.sourceHash,snapshotHash:enrollment.anchor.baseField.snapshotHash,physicalPitchSourceId:enrollment.physicalPitchSourceId,gameId:enrollment.gameId});expect(manifest.history.slice(0,-1)).toEqual(previous.history);
  expect(result.adoption).toEqual({kind:'received_renewal_adoption_v1',owner:physicalTable,sourceId:source.sourceId,renewalEnrollmentSourceId:enrollment.source.sourceId,renewalDecisionSourceId:motor.source.renewalDecisionSourceId,renewalMotorSourceId:motor.source.sourceId,playerId:enrollment.playerId,adoptedAt:at,executedThrough:at,ticksPerSecond:cut.ticksPerSecond,coverageThroughTick:composition.coverageThroughTick});
  expect({...composition.at,ticksPerSecond:composition.ticksPerSecond}).toEqual(cut);expect(motor.receipt.startAt).toEqual(at);expect(result.field.motion.world.moment).toEqual(oldField.motion.world.moment);expect(result.field.motion.cursor).toEqual(oldField.motion.cursor);expect(result.field.motion.carrierPlayerId).toBe(oldField.motion.carrierPlayerId);expect(result.field.baseContacts).toEqual([]);expect(result.field.motion.world.kind).not.toBe('boundary');
  expect(result.liveWork).toEqual({kind:'physical_continuation',sourceId:source.sourceId,originProcessSourceId:enrollment.originProcessSourceId,playerId:enrollment.playerId,dueTick:cut.tick});expect(composition.contributors).toHaveLength(10);expect(result.field.motion.actors).toHaveLength(50);expect(new Set(composition.contributors.map(p=>p.playerId)).size).toBe(10);
  expect(composition).toMatchObject({version:'received_renewal_adoption_composition_v1',physicalPitchSourceId:enrollment.physicalPitchSourceId,renewalEnrollmentSourceId:enrollment.source.sourceId,renewalDecisionSourceId:motor.source.renewalDecisionSourceId,renewalMotorSourceId:motor.source.sourceId,originProcessSourceId:enrollment.originProcessSourceId,sourceCoverage:'received_receiver_only_v1'});expect(composition.commands).toEqual(composition.contributors.map(p=>p.command));
  const roles=['body','glove','left_foot','right_foot','tag_hand'];
  const actorKey=(a:{playerId:string;primitive:{role:string}})=>JSON.stringify([a.playerId,a.primitive.role]),expectedActorKeys=composition.contributors.flatMap(p=>roles.map(role=>JSON.stringify([p.playerId,role]))).sort();expect(oldField.motion.actors.map(actorKey).sort()).toEqual(expectedActorKeys);expect(result.field.motion.actors.map(actorKey).sort()).toEqual(expectedActorKeys);expect(new Set(result.field.motion.actors.map(actorKey)).size).toBe(50);
  for(const p of composition.contributors){const anchor=enrollment.anchor.participants.find((a:{playerId:string})=>a.playerId===p.playerId),old=previous.execution.composition.contributors.find((a:{playerId:string})=>a.playerId===p.playerId);expect(anchor).toBeDefined();expect(p.personId).toBe(anchor.personId);expect(p.selfHash).toBe(anchor.selfHash);expect(hash(p.retainedCommand)).toBe(anchor.activeCommandHash);expect(hash(p.roleAuthorities)).toBe(anchor.roleAuthoritiesHash);expect(p.at).toEqual(at);expect(p.retainedRoles.map(r=>r.role).sort()).toEqual(roles);
    for(const role of p.retainedRoles){const authority=p.roleAuthorities.find(a=>a.role===role.role)!;expect(role.command).toEqual(authority.command);expect(role.acceptedThroughTick).toBe(authority.acceptedThroughTick);expect(role.acceptedThroughTick).toBeGreaterThan(cut.tick);expect(role.offsetAcceleration).toEqual(p.command.primitiveMotions.find(a=>a.role===role.role)!.offsetAcceleration);}
    if(p.playerId===enrollment.playerId){expect(p.kind).toBe('renewal_motor');expect(p.motorSourceId).toBe(motor.source.sourceId);expect(p.motorHash).toBe(receipt.acceptedHash);expect(p.command).toEqual(motor.receipt.command);expect(p.retainedRoles).toEqual(motor.receipt.retainedRoles);expect(p.rootAuthority).toEqual({owner:'actual_received_umpire_renewal_motors',sourceId:motor.source.sourceId,sourceHash:hash(motor.source),adoptionOwner:physicalTable,adoptionSourceId:source.sourceId,adoptionSourceHash:hash(source),acceptedThroughTick:motor.receipt.coverageEndTick});}
    else{expect(p.kind).toBe('retained');expect(p.motorSourceId).toBe(null);expect(p.motorHash).toBe(null);expect(p.command).toEqual(old.command);expect(p.rootAuthority).toEqual(old.rootAuthority);}
    expect(p.coverageThroughTick).toBe(Math.min(p.rootAuthority.acceptedThroughTick,...p.retainedRoles.map(r=>r.acceptedThroughTick),...(p.playerId===enrollment.playerId?[]:[p.retainedCommand.acceptedThroughTick])));
  }
  expect(composition.coverageThroughTick).toBe(Math.min(...composition.contributors.map(p=>p.coverageThroughTick)));expect(composition.coverageThroughTick).toBeGreaterThan(cut.tick);
  for(const actor of result.field.motion.actors){const old=oldField.motion.actors.find((a:{playerId:string;primitive:{role:string}})=>a.playerId===actor.playerId&&a.primitive.role===actor.primitive.role);expect(old).toBeDefined();const sampled=samplePiecewiseFieldActor(old,oldField.motion.world.moment),p=composition.contributors.find(p=>p.playerId===actor.playerId)!,role=p.retainedRoles.find(r=>r.role===actor.primitive.role)!,offset=role.offsetAcceleration,body=p.command.bodyAcceleration;
    expect(actor.primitive.startCenter).toEqual(sampled.center);expect(actor.primitive.startVelocity).toEqual(sampled.velocity);expect(actor.primitive.radius).toBe(old.primitive.radius);expect(actor.primitive.radius).toBe(role.radiusMeters);expect(actor.primitive.ticksPerSecond).toBe(cut.ticksPerSecond);expect(actor.primitive.startTick).toBe(cut.originTick);expect(actor.startElapsedSeconds).toBe(cut.elapsedSeconds);expect(actor.primitive.endTick).toBe(composition.coverageThroughTick);expect(actor.primitive.acceleration).toEqual({x:body.x+offset.x,y:body.y+offset.y,z:body.z+offset.z});
  }
  const after=readOnly(path,db=>{expect(receivedDefenderClaims(db,enrollment)).toHaveLength(9);expect(receivedRenewalClaims(db,enrollment)).toHaveLength(8);expect(receivedUnionClaims(db,enrollment)).toHaveLength(18);for(const selected of [{gameId:enrollment.gameId,playId:enrollment.playId},{gameId:enrollment.gameId,playId:enrollment.playId,physicalPitchSourceId:enrollment.physicalPitchSourceId}])expect(()=>beginActualLivePlayWrite(db,selected,{owner:physicalTable,sourceId:'renewal-genuine-blocked-after-adoption'})).toThrow(/received.*pending/i);return receivedGenuineCensus(db);});standalone();expect(after.schema).toEqual(before.schema);expect(after.tables).toHaveLength(80);expect(after.tables.reduce((n,t)=>n+t.rows.length,0)).toBe(154);
  for(const table of before.tables.filter(t=>![physicalTable,physicalHeadTable,headTable,journalTable].includes(t.name)))expect(after.tables.find(t=>t.name===table.name)).toEqual(table);
  expect(rows(after,physicalTable).filter(r=>r.source_id!==source.sourceId)).toEqual(rows(before,physicalTable));const added=rows(after,physicalTable).filter(r=>r.source_id===source.sourceId);expect(added).toHaveLength(1);expect(added[0]).toMatchObject({source_id:source.sourceId,source_json:json(source),source_hash:hash(source),snapshot_json:archive.json,snapshot_hash:archive.hash,revision:11,previous_source_id:source.previousExecutionSourceId,base_field_source_id:source.baseFieldSourceId,game_id:enrollment.gameId,physical_pitch_source_id:enrollment.physicalPitchSourceId});
  expect(rows(after,physicalHeadTable)).toEqual(rows(before,physicalHeadTable).map(r=>r.physical_pitch_source_id===enrollment.physicalPitchSourceId?{...r,source_id:source.sourceId,revision:11}:r));expect(rows(after,headTable)).toEqual([{...rows(before,headTable)[0],stage:4,owner:physicalTable,source_id:source.sourceId,adoption_source_id:source.sourceId}]);expect(rows(after,journalTable)).toHaveLength(4);expect(rows(after,journalTable).slice(0,3)).toEqual(rows(before,journalTable));
  const {__rowid,receipt_hash,...journalBody}=rows(after,journalTable)[3];expect(__rowid).toBe(4);expect(receipt_hash).toBe(hash(journalBody));expect(journalBody).toEqual({...Object.fromEntries(Object.entries(rows(before,journalTable)[2]).filter(([key])=>!['__rowid','receipt_hash'].includes(key))),sequence:4,owner:physicalTable,source_id:source.sourceId,source_version:source.sourceVersion,source_hash:hash(source),snapshot_hash:archive.hash,previous_receipt_hash:rows(before,journalTable)[2].receipt_hash});
  receivedGenuineSidecars(checkpoint.database,checkpoint.sidecars);const outputDatabaseSha256=receivedGenuineSha(readFileSync(path)),receiptPath=join(directory,'received-renewal-adoption.json'),fd=openSync(receiptPath,'wx',0o600);
  try{writeFileSync(fd,JSON.stringify({schema:'received_renewal_genuine_adoption_receipt_v1',reviewedHead:input.reviewedHead,reviewedSrc:input.reviewedSrc,predecessorCheckpoint:input.predecessor,inputDatabaseSha256:checkpoint.database.sha256,outputDatabaseSha256,source,acceptedArchive:manifest,acceptedArchiveJson:archive.json,acceptedArchiveHash:archive.hash,beforeCensusHash:receivedGenuineHash(before),afterCensusHash:receivedGenuineHash(after),changes:4,authorityCallbacks:callbacks,writes,inheritedOriginalTables:75,inheritedOriginalRows:145,originalRowException:'batted_world_field_execution_heads exact revision 10 to 11 CAS',originalAdmissionsPreserved:24,originalRolesPreserved:50,physicalAdvancement:false,adopted:true,pending:'physical_continuation',closureCredit:0},null,2)+'\n');fsyncSync(fd);}finally{closeSync(fd);}
  checkpointProgress('receipt_closed',{sourceId:source.sourceId,receiptSha256:receivedGenuineSha(readFileSync(receiptPath)),outputDatabaseSha256,nativeConnectionsClosed:true});
});
