import {existsSync,mkdtempSync,readFileSync,rmSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {expect,it} from 'vitest';
import {validateContinuationPredecessor} from './TerminalContinuationFixtureInputs.test-support';
import {createPitchStepTrace} from './TerminalContinuationPitchStep.test-support';
const moduleId='./TerminalClosureHandoff.test-support';
const api=async()=>{const m=existsSync(new URL('./TerminalClosureHandoff.test-support.ts',import.meta.url))?await import(/* @vite-ignore */moduleId):{};expect(typeof m.captureClosureHandoffInput,'CLOSURE_HANDOFF_API_MISSING').toBe('function');return m as any;};
const pin={path:'/private/pin.json',sha256:'a'.repeat(64)};
const input=()=>({version:'terminal_closure_handoff_v1',nativeReleased:false,sourceTree:'a'.repeat(40),qualifiedPhysical:pin,recipe:pin,destinationDirectory:'/private/new',tracePath:'/private/new/trace.jsonl',receiptPath:'/private/new/receipt.json'});
const origin={kind:'qualified_single_pitch_chain',qualifiedInput:pin,physicalReceipt:pin,aggregateP1Credit:0};
const receipt=()=>({version:'terminal_continuation_stage_v2',stage:'closure_queued',sourceTree:'a'.repeat(40),input:{path:'/private/input.sqlite',sha256:'b'.repeat(64)},output:{path:'/private/output.sqlite',sha256:'c'.repeat(64)},recipeHash:'d'.repeat(64),predecessorReceiptHash:'a'.repeat(64),allHandlesClosed:true,reopened:true,originalRowsPreserved:true,ownerReceipts:{},twoPriorCompletionLineage:false,splitPhysicalOrigin:origin});
// Structural Source/control contracts only. Genuine owner qualification is held.
it('HC-S01 captures strict inert handoff controls without caller Match or P1 status',async()=>{const m=await api();expect(m.captureClosureHandoffInput(input())).toEqual(input());expect(()=>m.captureClosureHandoffInput({...input(),p1Passed:true})).toThrow();let calls=0;const x=input();Object.defineProperty(x,'sourceTree',{enumerable:true,get(){calls++;return'a'.repeat(40);}});expect(()=>m.captureClosureHandoffInput(x)).toThrow();expect(calls).toBe(0);});
it('HC-S02 rejects an unreleased handoff before input or database access',async()=>{const m=await api();expect(()=>m.runTerminalClosureHandoff(input())).toThrow(/reviewed and released/);});
it('HC-S03 requires the actual qualified TAKE-2 strikeout and rejects an aggregate P1 substitute',async()=>{const m=await api(),q={version:'terminal_continuation_pitch_step_qualified_input_v1',step:'take_2',qualified:true,allHandlesClosed:true,reopened:true,originalRowsPreserved:true,aggregateP1Credit:0,artifact:pin,physical:{sourceId:'terminal-continuation-k-take-2',progressRevision:3,status:'strikeout',count:null}};expect(m.validateClosurePhysicalInput(q)).toEqual(q);for(const d of [{step:'take_1'},{qualified:false},{aggregateP1Credit:1},{physical:{...q.physical,status:'active'}},{version:'terminal_continuation_stage_v1',stage:'physical_k'}])expect(()=>m.validateClosurePhysicalInput({...q,...d})).toThrow();});
it('HC-S04 accepts explicit split-pitch provenance only after a real queue stage',async()=>{await api();const q=receipt();expect(validateContinuationPredecessor('closure_completed',q)).toEqual(q);expect(()=>validateContinuationPredecessor('closure_completed',{...q,predecessorReceiptHash:'e'.repeat(64)}),'CLOSURE_ORIGIN_HASH_DISCONNECTED').toThrow();expect(()=>validateContinuationPredecessor('closure_queued',{...q,stage:'physical_k'})).toThrow();expect(()=>validateContinuationPredecessor('closure_completed',{...q,splitPhysicalOrigin:{...origin,aggregateP1Credit:1}})).toThrow();});
it('HC-S05 preserves exact v1 shape and carries the new origin only through later closure stages',async()=>{const m=await api(),q=receipt(),{splitPhysicalOrigin:_origin,...rest}=q,legacy={...rest,version:'terminal_continuation_stage_v1'};expect(JSON.stringify(validateContinuationPredecessor('closure_completed',legacy))).toBe(JSON.stringify(legacy));expect(()=>validateContinuationPredecessor('closure_completed',{...legacy,splitPhysicalOrigin:origin})).toThrow();expect(m.closureContinuationReceiptFields(q)).toEqual({version:'terminal_continuation_stage_v2',splitPhysicalOrigin:origin});expect(m.closureContinuationReceiptFields(legacy)).toEqual({version:'terminal_continuation_stage_v1'});});
it('HC-S06 persists an authentic-owner-return observation before later queue readback',async()=>{await api();const directory=mkdtempSync(join(tmpdir(),'closure-handoff-')),path=join(directory,'trace.jsonl'),trace=createPitchStepTrace(path)as any;try{trace.returnedClosure('enqueue',{source:{sourceId:'terminal-continuation-k-close'},proposal:{scope:'structural'},status:'PENDING'});const event=JSON.parse(readFileSync(path,'utf8').trim());expect(event.event).toBe('closure_returned');expect(event.sourceId).toBe('terminal-continuation-k-close');expect(event.status).toBe('PENDING');}finally{trace.close();rmSync(directory,{recursive:true,force:true});}});
