import assert from 'node:assert/strict';
import { test } from 'vitest';
import { fixture, flight, value, change } from './BattingFixtures.test-support';
import { physical } from './BattingPhysicalFixtures.test-support';
import { resolveBattingExecution } from './BattingResolution';
import { prepareBattingExecution } from './BattingCommitment';
import { sampleSwingStateV1 } from '../../../sim/contact/SwingKinematicsV1';
const resolve=(r=physical())=>value(resolveBattingExecution(r));
test('neutral prepared swing physically contacts the ball and records canonical contact',()=>{const p=resolve();assert.equal(p.resolution.kind,'recorded_swing');if(p.resolution.kind!=='recorded_swing')return;assert.equal(p.resolution.physical.kind,'contact');assert.equal(p.resolution.timeline.status.kind,'batted_ball_pending');});
test('same frozen commitment against displaced actual flight misses without replanning',()=>{const r=physical(),a=resolve(r),b=resolve(change(r,d=>d.actualTrajectory.start.position.x=3));assert.deepEqual(a.commitment,b.commitment);assert.equal(b.resolution.kind,'recorded_swing');if(b.resolution.kind==='recorded_swing')assert.equal(b.resolution.physical.kind,'swinging_miss');});
test('early commitment loses refined information and causally misses the same actual pitch',()=>{const a=resolve(),b=resolve(physical(fixture('IMPATIENCE',{swingDecisionShiftTicks:-30000})));assert.equal(a.commitment.predictionId,'refined');assert.equal(b.commitment.predictionId,'coarse');if(a.resolution.kind==='recorded_swing' && b.resolution.kind==='recorded_swing'){assert.equal(a.resolution.physical.kind,'contact');assert.equal(b.resolution.physical.kind,'swinging_miss');}else assert.fail('not swings');});
test('late motor onset causes an actual physical miss',()=>{const p=resolve(physical(fixture('IMPATIENCE',{swingDecisionShiftTicks:120000})));assert.ok(p.commitment.motorDelayTicks>0);if(p.resolution.kind==='recorded_swing')assert.equal(p.resolution.physical.kind,'swinging_miss');else assert.fail('not swing');});
test('take resolves through aerodynamic plate crossing, not a guessed result',()=>{const p=resolve(physical(change(fixture(),d=>d.source.directive='TAKE')));assert.equal(p.resolution.kind,'recorded_take');if(p.resolution.kind==='recorded_take'){assert.equal(p.resolution.physical.kind,'called_strike');assert.deepEqual(p.resolution.timeline.status,{kind:'active',count:{balls:0,strikes:1}});}});
test('ball four is counted by existing canonical rules',()=>{const p=resolve(physical(change(fixture(),d=>{d.source.directive='TAKE';d.source.count.balls=3;}),flight(3)));assert.equal(p.resolution.timeline.status.kind,'walk');});
test('third physical swinging strike is counted by existing rules',()=>{const p=resolve(physical(change(fixture(),d=>d.source.count.strikes=2),flight(3)));assert.equal(p.resolution.timeline.status.kind,'strikeout');});
test('no plate crossing remains unresolved on a take',()=>{const p=resolve(physical(change(fixture(),d=>d.source.directive='TAKE'),change(flight(),d=>d.start.velocity.z=40)));assert.equal(p.resolution.kind,'unresolved');assert.equal(p.resolution.timeline.events.length,0);});
test('rigid bat length is preserved throughout the committed motion',()=>{const p=value(prepareBattingExecution(fixture())).commitment!,t=p.trajectory!;for(const tick of [t.startTick,Math.floor((t.startTick+t.contactTick)/2),t.contactTick,t.endTick]){const s=sampleSwingStateV1(t,tick),a=s.pose.grip,b=s.pose.tip;assert.ok(Math.abs(Math.hypot(a.x-b.x,a.y-b.y,a.z-b.z)-t.batLengthM)<1e-10);}});
test('actual flight interval exhaustion rejects instead of inventing a miss',()=>assert.equal(resolveBattingExecution(change(physical(),d=>d.actualTrajectory.endTick=200000)).ok,false));
test('early physical execution cannot bypass motor commitment',()=>assert.equal(resolveBattingExecution(change(physical(),d=>d.currentFrame.time.tick--)).ok,false));
test('late physical execution cannot silently backdate the swing',()=>assert.equal(resolveBattingExecution(change(physical(),d=>d.currentFrame.time.tick++)).ok,false));
test('other ball cannot use the committed plan',()=>assert.equal(resolveBattingExecution(change(physical(),d=>d.ballId='other')).ok,false));
test('stale timeline count cannot receive this pitch',()=>assert.equal(resolveBattingExecution(change(physical(),d=>d.timeline.status.count.strikes=1)).ok,false));
test('invalid source count is rejected before a physical plan',()=>assert.equal(prepareBattingExecution(change(fixture(),d=>d.source.count.strikes=3)).ok,false));
test('physical forecast is deterministic and leaves both inputs unchanged',()=>{const r=physical(),before=structuredClone(r),a=resolve(r),b=resolve(r);assert.deepEqual(a,b);assert.deepEqual(r,before);assert.ok(Object.isFrozen(a.resolution.timeline.events));});
