import {mkdtempSync,readFileSync,rmSync,fsyncSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {afterEach,expect,it,vi} from 'vitest';
import * as hooks from './TerminalCompletionObservationHooks.test-support';
import {SqliteOfficialStateStore} from '../../../src/host/SqliteOfficialStateStore';
import * as scoring from '../../../src/host/SqliteOfficialScoringStore';
import * as effort from '../../../src/host/world/SqliteOfficialPitchWorkloadStore';
import * as workload from '../../../src/host/world/SqlitePlayerWorkloadRecoveryStore';
import * as closure from '../../../src/host/world/SqlitePhysicalPlayClosureStore';
import * as exported from './ReturnedOwnerObservation.test-support';
const api=()=>{const m=exported as any;expect(typeof m.forwardObservedOwner,'COMPLETION_OBSERVER_API_MISSING').toBe('function');expect(typeof m.createReturnedOwnerObservation,'COMPLETION_OBSERVER_API_MISSING').toBe('function');return m;};
const roots:string[]=[];afterEach(()=>{for(const root of roots.splice(0))rmSync(root,{recursive:true,force:true});});
const path=()=>{const root=mkdtempSync(join(tmpdir(),'completion-observer-structural-'));roots.push(root);return join(root,'observations');};
// Structural fake owners below establish instrumentation only, never original physical proofs.
it('CO-S01 preserves original receiver arguments and exact frozen returned identity',()=>{const m=api(),arg={},result=Object.freeze({ok:true}),seen:unknown[]=[];const owner=Object.freeze({apply(this:unknown,input:unknown){expect(this).toBe(owner);expect(input).toBe(arg);seen.push('owner');return result;}});const observer={returned(...args:unknown[]){seen.push(args);}};const facade=m.forwardObservedOwner(owner,{apply:'official'},observer);expect(facade.apply(arg)).toBe(result);expect(seen.length).toBe(2);expect(Object.isFrozen(facade)).toBe(true);expect(owner.apply).not.toBe(facade.apply);});
it('CO-S02 forwards unobserved reads and close to the original frozen owner',()=>{const m=api(),result={revision:2};let closed=0;const owner=Object.freeze({read(this:unknown){expect(this).toBe(owner);return result;},close(this:unknown){expect(this).toBe(owner);closed++;},apply(){return result;}});const facade=m.forwardObservedOwner(owner,{apply:'workload'},{returned(){throw Error('unexpected observation');}});expect(facade.read()).toBe(result);facade.close();expect(closed).toBe(1);expect(result).toEqual({revision:2});});
it('CO-S03 preserves the exact owner exception without a returned observation',()=>{const m=api(),failure=Error('owner failed');let observed=0;const owner=Object.freeze({apply(){throw failure;}});const facade=m.forwardObservedOwner(owner,{apply:'scoring'},{returned(){observed++;}});let thrown;try{facade.apply();}catch(e){thrown=e;}expect(thrown).toBe(failure);expect(observed).toBe(0);});
it('CO-S04 fails after one real return if its observation fails without retry or mutation',()=>{const m=api(),failure=Error('fsync failed'),result={revision:2};let calls=0,after=0;const owner=Object.freeze({apply(){calls++;return result;}});const facade=m.forwardObservedOwner(owner,{apply:'workload'},{returned(){throw failure;}});expect(()=>{facade.apply();after++;}).toThrow(failure);expect(calls).toBe(1);expect(after).toBe(0);expect(result).toEqual({revision:2});});
it('CO-S05 fsyncs actual returned values before exposing a readable return event',()=>{const m=api(),directory=path();let syncs=0;const recorder=m.createReturnedOwnerObservation(directory,{sync(fd:number){fsyncSync(fd);syncs++;}});const result={revision:2,playerId:'p2'},owner=Object.freeze({apply(){return result;}});const facade=m.forwardObservedOwner(owner,{apply:'workload'},recorder);expect(facade.apply('actual-event',1)).toBe(result);expect(syncs).toBeGreaterThanOrEqual(3);const event=JSON.parse(readFileSync(join(directory,'events.jsonl'),'utf8').trim());expect(event.operation).toBe('workload');expect(JSON.parse(readFileSync(event.result.path,'utf8'))).toEqual(result);expect(event.result.sha256).toMatch(/^[a-f0-9]{64}$/);const first=recorder.close();expect(recorder.close()).toEqual(first);});
it('CO-S06 retains separate actual effort workload and completion retry results in order',()=>{const m=api(),directory=path(),recorder=m.createReturnedOwnerObservation(directory),activity={kind:'MATCH',sourceEventId:'actual-effort',effortUnits:6},after={playerId:'p2',revision:2},completion={sourceId:'terminal-continuation-k-close',workload:{activity,before:{revision:1},after}};const a=m.forwardObservedOwner(Object.freeze({accept(){return activity;}}),{accept:'effort'},recorder),w=m.forwardObservedOwner(Object.freeze({apply(){return after;}}),{apply:'workload'},recorder),c=m.forwardObservedOwner(Object.freeze({resume(){return completion;}}),{resume:'completion'},recorder);expect(a.accept()).toBe(activity);expect(w.apply()).toBe(after);expect(c.resume()).toBe(completion);expect(c.resume()).toBe(completion);recorder.close();const events=readFileSync(join(directory,'events.jsonl'),'utf8').trim().split('\n').map(line=>JSON.parse(line));expect(events.map(e=>e.operation)).toEqual(['effort','workload','completion','completion']);expect(events[2].result.sha256).toBe(events[3].result.sha256);expect(JSON.parse(readFileSync(events[1].result.path,'utf8'))).toEqual(after);});
it('CO-S07 preserves class receiver and original returned identity in prototype hooks',()=>{const m=api();expect(typeof m.observeReturnedMethod,'COMPLETION_HOOK_API_MISSING').toBe('function');const result={applied:true};class Owner{private value=result;apply(input:unknown){expect(input).toBe(result);return this.value;}}const owner=new Owner(),events:unknown[]=[];const wrapped=m.observeReturnedMethod(Owner.prototype.apply,'official.applyAndActivate',{returned(...args:unknown[]){events.push(args);}});expect(wrapped.call(owner,result)).toBe(result);expect(events.length).toBe(1);});
it('CO-S08 restores installed hooks in reverse order on installation failure',()=>{const m=api();expect(typeof m.installObservationHooks,'COMPLETION_HOOK_API_MISSING').toBe('function');const restored:number[]=[],failure=Error('install failed');let thrown;try{m.installObservationHooks((register:(restore:()=>void)=>void)=>{register(()=>restored.push(1));register(()=>restored.push(2));throw failure;});}catch(e){thrown=e;}expect(thrown).toBe(failure);expect(restored).toEqual([2,1]);const clean=m.installObservationHooks((register:(restore:()=>void)=>void)=>register(()=>restored.push(3)));clean();clean();expect(restored).toEqual([2,1,3]);});
it('CO-S09 requires each actual owner return and only the final completion retry',()=>{const m=api();expect(typeof m.assertReturnedCompletion,'COMPLETION_HOOK_API_MISSING').toBe('function');const official={receipt:{applicationId:'terminal-continuation-k-application'}},scoring={scoringApplicationId:'terminal-continuation-k-score'},activity={kind:'MATCH',effortUnits:6},after={careerId:'career-a',playerId:'p2',revision:2},completion={sourceId:'terminal-continuation-k-close',gameId:'game-1',playId:8,official,scoring,workload:{activity,before:{revision:1},after}},rows=[{operation:'official.applyAndFinalize',value:official},{operation:'scoring',value:scoring},{operation:'effort',value:activity},{operation:'workload',value:after},{operation:'completion',value:completion},{operation:'completion',value:completion}];expect(()=>m.assertReturnedCompletion(rows)).not.toThrow();expect(()=>m.assertReturnedCompletion(rows.filter(r=>r.operation!=='effort'))).toThrow();expect(()=>m.assertReturnedCompletion([...rows,rows[2]])).toThrow();expect(()=>m.assertReturnedCompletion(rows.map(r=>r.operation==='workload'?{...r,value:completion.workload}:r))).toThrow();});

it('CO-S10 installs and restores every actual module interception without opening owners',()=>{const h=hooks as any;expect(typeof h.installCompletionOwnerObservationHooks,'COMPLETION_WIRING_API_MISSING').toBe('function');const current=()=>[SqliteOfficialStateStore.prototype.applyAndActivate,SqliteOfficialStateStore.prototype.applyAndFinalize,scoring.openSqliteOfficialScoringStore,effort.openSqliteOfficialPitchWorkloadStore,workload.openSqlitePlayerWorkloadRecoveryStore,closure.openSqlitePhysicalPlayClosureStore],before=current(),restore=h.installCompletionOwnerObservationHooks({returned(){throw Error('owners must not open in this structural wiring test');}});try{expect(current().every(fn=>vi.isMockFunction(fn))).toBe(true);}finally{restore();}current().forEach((fn,i)=>expect(fn).toBe(before[i]));});
