import {expect,it} from 'vitest';
import {actorHash as hash} from '../../../src/host/world/PhysicalPlateAppearanceActorEvidenceFromSqlite';
import * as exported from './TerminalCompletedEndpointRecovery.test-support';
const api=()=>{const m=exported as any;expect(typeof m.captureCompletedAdmissionResumeInput,'ADMISSION_RESUME_API_MISSING').toBe('function');return m;};
const pin=(path='/private/control.json')=>({path,sha256:'a'.repeat(64)});
const input=()=>({version:'terminal_completed_admission_resume_v1',nativeReleased:false,sourceTree:'b'.repeat(40),admissionReceipt:pin('/private/recovery/admission/receipt.json'),interruptedTuple:pin(),destinationDirectory:'/private/new',receiptPath:'/private/new/receipt.json'});
// Structural metadata and row-seal contracts only; no genuine owner proof is mocked.
it('CA-S01 captures inert continuation controls and refuses unreleased execution before IO',()=>{const m=api(),i=input();expect(m.captureCompletedAdmissionResumeInput(i)).toEqual(i);expect(()=>m.runCompletedAdmissionResume(i)).toThrow('not been reviewed and released');let reads=0;Object.defineProperty(i,'admissionReceipt',{enumerable:true,get(){reads++;return pin();}});expect(()=>m.captureCompletedAdmissionResumeInput(i)).toThrow();expect(reads).toBe(0);});
it('CA-S02 requires the actual closed admission and preserves interrupted attempts at zero credit',()=>{const m=api();expect(typeof m.assertClosedAdmissionResumeLineage,'ADMISSION_RESUME_LINEAGE_MISSING').toBe('function');const i=input(),prior={sourceTree:i.sourceTree,tuple:pin(),destinationDirectory:'/private/recovery'},admission={version:'terminal_completed_endpoint_admission_v1',sourceTree:i.sourceTree,originalFailedTuple:prior.tuple,originalFailedAttemptCredit:0,artifact:pin('/private/recovery/admission/game.sqlite'),completionResultSha256:'a'.repeat(64),ownerReceipts:{},allHandlesClosed:true,originalRowsPreserved:true},manifest={version:'interrupted_completed_recovery_tuple_v1',credit:0,admissionReceipt:i.admissionReceipt,files:[{...admission.artifact,exists:true,bytes:4096},...['-wal','-shm','-journal'].map(s=>({path:admission.artifact.path+s,exists:false}))]};expect(()=>m.assertClosedAdmissionResumeLineage(i,manifest,prior,admission)).not.toThrow();for(const bad of [{...admission,originalFailedAttemptCredit:1},{...admission,allHandlesClosed:false},{...admission,artifact:pin('/private/other.sqlite')}])expect(()=>m.assertClosedAdmissionResumeLineage(i,manifest,prior,bad)).toThrow();expect(()=>m.assertClosedAdmissionResumeLineage(i,{...manifest,files:manifest.files.map((x:any)=>x.path.endsWith('-wal')?{...x,exists:true}:x)},prior,admission)).toThrow();});
it('CA-S03 binds raw setup only to the closed admission seals before the real resume proof',()=>{const m=api();expect(typeof m.assertAdmissionResumeRawClosure,'ADMISSION_RESUME_ROW_SEAL_MISSING').toBe('function');const source={sourceId:'terminal-continuation-k-close'},proposal={gameId:'game-1'},result={playId:8};const row={source_id:source.sourceId,status:'COMPLETED',source_json:JSON.stringify(source),source_hash:hash(source),proposal_json:JSON.stringify(proposal),proposal_hash:hash(proposal),result_json:JSON.stringify(result)},admission={completionResultSha256:hash(result),ownerReceipts:{closure:{sourceId:source.sourceId,status:'COMPLETED',sourceHash:hash(source),proposalHash:hash(proposal)}}};expect(m.assertAdmissionResumeRawClosure(row,admission)).toEqual({source,proposal,result});for(const bad of [{...row,status:'PENDING'},{...row,result_json:'{}'},{...row,source_hash:'c'.repeat(64)},{...row,proposal_json:'{}'}])expect(()=>m.assertAdmissionResumeRawClosure(bad,admission)).toThrow();});
