import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {closeSync,constants,copyFileSync,existsSync,fsyncSync,lstatSync,mkdirSync,openSync,readFileSync,realpathSync,writeFileSync} from 'node:fs';
import {basename,dirname,isAbsolute,join} from 'node:path';
import {vi} from 'vitest';
import {cloneInert} from '../../../src/core/adjudication/OfficialWindowPolicy';
import {SqliteOfficialStateStore} from '../../../src/host/SqliteOfficialStateStore';
import * as scoring from '../../../src/host/SqliteOfficialScoringStore';
import * as effort from '../../../src/host/world/SqliteOfficialPitchWorkloadStore';
import * as workloadOwner from '../../../src/host/world/SqlitePlayerWorkloadRecoveryStore';
import {SqliteOfficialParticipationStore} from '../../../src/host/world/SqliteOfficialParticipationStore';
import {openSqliteOfficialInitialWorldStore} from '../../../src/host/world/SqliteOfficialInitialWorldStore';
import {openSqlitePlayerPersonLinkStore} from '../../../src/host/world/SqlitePlayerPersonLinkStore';
import {openSqlitePlayerPitchTimingStore} from '../../../src/host/world/SqlitePlayerPitchTimingStore';
import {openSqlitePlayerReleaseGeometryStore} from '../../../src/host/world/SqlitePlayerReleaseGeometryStore';
import {openSqlitePitchFatiguePolicyStore} from '../../../src/host/world/SqlitePitchFatiguePolicyStore';
import {openSqlitePhysicalPitchProgressStore} from '../../../src/host/world/SqlitePhysicalPitchProgressStore';
import {openSqlitePhysicalPlayClosureStore} from '../../../src/host/world/SqlitePhysicalPlayClosureStore';
import {readPhysicalClosureProposal,assertPhysicalClosureStages,readPhysicalClosureWorkload} from '../../../src/host/world/PhysicalPlayClosureEvidenceFromSqlite';
import {foulTerminalPostPlayCompletionEvidenceFromSqlite} from '../../../src/host/world/ActualFoulTerminalPostPlayCompletionEvidenceFromSqlite';
import {readActualRoleWorkloadState} from '../../../src/host/world/ActualRoleWorkloadState';
import {actorJson as json,actorHash as hash} from '../../../src/host/world/PhysicalPlateAppearanceActorEvidenceFromSqlite';
import {fileHash,rawCensus,schemaCensus} from '../../../src/host/world/ActualFoulTerminalAcknowledgementCutover.test-support';
import {withSqliteReadTransaction} from '../../../src/host/world/SqliteReadTransaction.test-support';
import {withBattedVenueLegalReadSnapshot} from '../../../src/host/world/SqliteBattedVenueLegalPolicyStore';
import {createPitchStepTrace} from '../../../src/host/world/TerminalContinuationPitchStep.test-support';
import {terminalContinuationFixtureIds as ids,validateContinuationPredecessor,assertContinuationRows,type TerminalContinuationStageReceipt} from '../../../src/host/world/TerminalContinuationFixtureInputs.test-support';
import {assertReturnedCompletion,createReturnedOwnerObservation,installObservationHooks} from './ReturnedOwnerObservation.test-support';
const {DatabaseSync}=createRequire(import.meta.url)('node:sqlite')as typeof import('node:sqlite');
type Pin=Readonly<{path:string;sha256:string}>;
export type CompletedRecoveryInput=Readonly<{version:'terminal_completed_endpoint_recovery_v1';nativeReleased:boolean;sourceTree:string;tuple:Pin;inspection:Pin;queueReceipt:Pin;queueQualification:Pin;recipe:Pin;destinationDirectory:string;receiptPath:string}>;
const same=(a:unknown,b:unknown,message:string)=>assert.equal(json(a),json(b),message);
const fields=(v:unknown,names:string[])=>v!==null&&typeof v==='object'&&!Array.isArray(v)&&json(Object.keys(v).sort())===json(names.sort());
const validPin=(p:Pin)=>fields(p,['path','sha256'])&&typeof p.path==='string'&&isAbsolute(p.path)&&/^[a-f0-9]{64}$/.test(p.sha256);
export const captureCompletedRecoveryInput=(raw:CompletedRecoveryInput)=>{const i=cloneInert(raw);assert(fields(i,['version','nativeReleased','sourceTree','tuple','inspection','queueReceipt','queueQualification','recipe','destinationDirectory','receiptPath'])&&i.version==='terminal_completed_endpoint_recovery_v1'&&typeof i.nativeReleased==='boolean'&&/^[a-f0-9]{40}$/.test(i.sourceTree)&&[i.tuple,i.inspection,i.queueReceipt,i.queueQualification,i.recipe].every(validPin),'completed recovery controls differ');assert(isAbsolute(i.destinationDirectory)&&isAbsolute(i.receiptPath)&&dirname(i.receiptPath)===i.destinationDirectory,'completed recovery output paths differ');return i;};
export const validateCompletedRecoveryTuple=(raw:unknown)=>{const m=cloneInert(raw)as any;assert(fields(m,['schema','originalAggregateCredit','terminal','config','input','events','returnedValues','files'])&&m.schema==='capped_ordinary_completion_tuple_v1'&&m.originalAggregateCredit===0&&[m.terminal,m.config,m.input,m.events].every(validPin)&&Array.isArray(m.returnedValues)&&m.returnedValues.length===6&&m.returnedValues.every(validPin),'completed recovery failed-attempt metadata differs');assert(Array.isArray(m.files)&&m.files.length===4,'completed recovery requires the full tuple');const names=['game.sqlite','game.sqlite-wal','game.sqlite-shm','game.sqlite-journal'];const parent=dirname(m.files[0].path);for(const [index,row]of m.files.entries()){assert(isAbsolute(row.path)&&dirname(row.path)===parent&&basename(row.path)===names[index],'completed recovery tuple paths differ');if(index<3)assert(row.exists===true&&Number.isSafeInteger(row.bytes)&&row.bytes>0&&/^[a-f0-9]{64}$/.test(row.sha256),'completed recovery main/WAL/SHM is absent or empty');else assert(row.exists===false,'completed recovery unexpected journal');}return m;};
export const forbidRecoveryOwnerCalls=<T extends object>(owner:T,names:readonly string[]):T=>{const descriptors=Object.getOwnPropertyDescriptors(owner),out=Object.create(Object.getPrototypeOf(owner));for(const name of names)assert(typeof descriptors[name]?.value==='function','recovery effect method is missing');for(const key of Reflect.ownKeys(descriptors)){const d=Reflect.get(descriptors,key)as PropertyDescriptor;assert('value'in d,'recovery facade requires data properties');const original=d.value;Object.defineProperty(out,key,{...d,value:typeof original==='function'?function(...args:unknown[]){if(typeof key==='string'&&names.includes(key))throw new Error('recovery forbids effect owner: '+key);return Reflect.apply(original,owner,args);}:original});}return Object.freeze(out)as T;};
export const assertRecoveryQueueBinding=(actual:Readonly<{sourceId:string;sourceHash:string;proposalHash:string}>,queued:any)=>{assert(queued?.status==='PENDING','recovery queued owner status differs');same(actual,{sourceId:queued.sourceId,sourceHash:queued.sourceHash,proposalHash:queued.proposalHash},'recovery changed the accepted queue Source or proposal');};
export const recoveredContinuationReceipt=(v:any):TerminalContinuationStageReceipt=>{assert(v.admission.closed===true&&validPin(v.admission.artifact)&&validPin(v.admission.receipt)&&validPin(v.output)&&v.admission.artifact.path!==v.output.path&&v.queue.version==='terminal_continuation_stage_v2'&&v.queue.stage==='closure_queued'&&v.queue.sourceTree===v.sourceTree&&v.queue.recipeHash===v.recipe.sha256&&v.queue.splitPhysicalOrigin.aggregateP1Credit===0,'recovered completed admission/provenance differs');return{version:'terminal_continuation_stage_v2',stage:'closure_completed',sourceTree:v.sourceTree,input:v.admission.artifact,output:v.output,recipeHash:v.recipe.sha256,predecessorReceiptHash:v.admission.receipt.sha256,allHandlesClosed:true,reopened:true,originalRowsPreserved:true,twoPriorCompletionLineage:false,splitPhysicalOrigin:v.queue.splitPhysicalOrigin,ownerReceipts:v.owners};};
const pin=(p:Pin)=>{assert(validPin(p)&&realpathSync(p.path)===p.path&&lstatSync(p.path).isFile(),'recovery pin is not canonical');assert.equal(fileHash(p.path),p.sha256,'recovery pinned bytes changed');};
const readPin=<T=any>(p:Pin):T=>{pin(p);return cloneInert(JSON.parse(readFileSync(p.path,'utf8')))as T;};
const closed=(path:string)=>{for(const suffix of ['-wal','-shm','-journal'])assert(!existsSync(path+suffix),'recovery checkpoint is not closed');};
const syncDir=(path:string)=>{const fd=openSync(path,'r');try{fsyncSync(fd);}finally{closeSync(fd);}};
const syncFile=(path:string)=>{const fd=openSync(path,'r');try{fsyncSync(fd);}finally{closeSync(fd);}};
const save=(path:string,value:unknown)=>{const fd=openSync(path,'wx',0o600);try{writeFileSync(fd,JSON.stringify(value,null,2)+'\n');fsyncSync(fd);}finally{closeSync(fd);}syncDir(dirname(path));return{path,sha256:fileHash(path)};};
const effectGuards=()=>installObservationHooks(register=>{
 for(const name of ['applyAndActivate','applyAndFinalize']as const){const spy=vi.spyOn(SqliteOfficialStateStore.prototype,name);register(()=>spy.mockRestore());spy.mockImplementation(()=>{throw new Error('recovery forbids effect owner: official');});}
 const so=scoring.openSqliteOfficialScoringStore,ss=vi.spyOn(scoring,'openSqliteOfficialScoringStore');register(()=>ss.mockRestore());ss.mockImplementation((...args)=>forbidRecoveryOwnerCalls(Reflect.apply(so,scoring,args),['apply']));
 const eo=effort.openSqliteOfficialPitchWorkloadStore,es=vi.spyOn(effort,'openSqliteOfficialPitchWorkloadStore');register(()=>es.mockRestore());es.mockImplementation((...args)=>forbidRecoveryOwnerCalls(Reflect.apply(eo,effort,args),['accept']));
 const wo=workloadOwner.openSqlitePlayerWorkloadRecoveryStore,ws=vi.spyOn(workloadOwner,'openSqlitePlayerWorkloadRecoveryStore');register(()=>ws.mockRestore());ws.mockImplementation((...args)=>forbidRecoveryOwnerCalls(Reflect.apply(wo,workloadOwner,args),['apply','initialize']));
});
/** Recovery consumes a full failed tuple, never its main file alone. The first
 * closed checkpoint is an authentic completed admission; the continuation view
 * then names that actual closed input. Original CO-N01 receives zero credit. */
export const runCompletedEndpointRecovery=(raw:CompletedRecoveryInput)=>{
 const input=captureCompletedRecoveryInput(raw);assert(input.nativeReleased===true,'completed recovery has not been reviewed and released');assert(!existsSync(input.destinationDirectory),'recovery output already exists');
 const observer=createReturnedOwnerObservation(input.destinationDirectory),timing=createPitchStepTrace(join(input.destinationDirectory,'spans.jsonl')),resources:{close():void}[]=[],restores:(()=>void)[]=[];
 const track=<T extends{close():void}>(v:T)=>{resources.push(v);return v;};const closeAll=()=>{const errors:unknown[]=[];while(resources.length)try{resources.pop()!.close();}catch(e){errors.push(e);}if(errors.length)throw new AggregateError(errors,'recovery handle cleanup failed');};let failed=false,primary:unknown;
 try{
  const metadata=timing.span('metadata',()=>{
   const tuple=validateCompletedRecoveryTuple(readPin(input.tuple)),inspection=readPin(input.inspection),terminal=readPin(tuple.terminal),config=readPin(tuple.config),priorRun=readPin(tuple.input),eventsText=readFileSync((pin(tuple.events),tuple.events.path),'utf8'),events=eventsText.trim().split('\n').map((line:string)=>JSON.parse(line));
   assert(terminal.status==='failed'&&terminal.originalChildExit===-15&&terminal.configSha256===tuple.config.sha256&&config.sourceIdentity.src===input.sourceTree&&priorRun.stage==='closure_completed'&&priorRun.nativeReleased===true,'failed completion attribution differs');same(terminal.remainingOwnedProcesses,[],'failed completion processes remain');same(terminal.before,terminal.after,'failed completion input groups changed');assert(config.stage==='closure_completed'&&config.sourceIdentity.head==='624f086a08a20f6dd2a40a8ff9dad9642e01094f'&&config.artifactEnvironment.TERMINAL_CONTINUATION_INPUT===tuple.input.path&&tuple.files[0].path===priorRun.destinationPath&&tuple.events.path===join(dirname(priorRun.destinationPath),'events.jsonl'),'failed completion tuple/control paths differ');same(priorRun.predecessorReceipt,input.queueReceipt,'failed completion Q1 differs');same(priorRun.recipe,input.recipe,'failed completion recipe differs');
   assert(inspection.kind==='raw_copy_inspection_only_no_original_owner_credit'&&inspection.actualClosureStatus==='COMPLETED'&&inspection.allSixReturnsHashVerified===true&&inspection.allReturnedValuesMatchSql===true&&inspection.originalTupleManifest.sha256===input.tuple.sha256,'recovery inspection identity differs');
   const returned=events.filter((e:any)=>e.event==='owner_returned');same(returned.map((e:any)=>e.result),tuple.returnedValues,'failed completion returned inventory differs');const values=returned.map((e:any)=>({operation:e.operation,value:readPin(e.result)}));assertReturnedCompletion(values);
   const queue=validateContinuationPredecessor('closure_completed',readPin(input.queueReceipt));assert(queue?.version==='terminal_continuation_stage_v2');assert(queue.sourceTree===input.sourceTree&&queue.recipeHash===input.recipe.sha256,'Q1 source/recipe differs');readPin(input.recipe);
   const queueQualification=readPin(input.queueQualification);assert(queueQualification.version==='terminal_continuation_queue_qualified_input_v1'&&queueQualification.qualified===true,'Q1 qualification differs');same(queueQualification.qualification.receipt,input.queueReceipt,'Q1 qualification receipt differs');same(queueQualification.artifact,queue.output,'Q1 qualification artifact differs');const conservation=readPin(queueQualification.qualification.conservation),queueCensusPins=conservation.rawEvidence.filter((p:Pin)=>basename(p.path)==='after-census.json');assert(queueCensusPins.length===1,'Q1 row conservation pin differs');const queueCensus=readPin(queueCensusPins[0]);pin(queue.output);closed(queue.output.path);
   const expected=readPin(inspection.census),verifyTuple=()=>{for(const row of tuple.files){if(row.exists){pin({path:row.path,sha256:row.sha256});const stat=lstatSync(row.path);assert(stat.size===row.bytes&&stat.dev===row.device&&stat.ino===row.inode,'failed tuple file identity changed');}else assert(!existsSync(row.path),'failed tuple journal appeared');}};verifyTuple();return{tuple,queue,queueCensus,expected,original:values[4].value,verifyTuple};
  });
  restores.push(effectGuards());
  const admissionDirectory=join(input.destinationDirectory,'admission');mkdirSync(admissionDirectory,{mode:0o700});const admissionPath=join(admissionDirectory,'game.sqlite');
  timing.span('copy',()=>{for(const row of metadata.tuple.files)if(row.exists){const path=join(admissionDirectory,basename(row.path));copyFileSync(row.path,path,constants.COPYFILE_EXCL);assert.equal(fileHash(path),row.sha256);}});
  const admissionDb=track(new DatabaseSync(admissionPath)),before=rawCensus(admissionDb),schema=schemaCensus(admissionDb);same(before,metadata.expected.rows,'full-tuple recovery rows differ');same(schema,metadata.expected.schema,'full-tuple recovery schema differs');
  const read=<T>(db:InstanceType<typeof DatabaseSync>,body:()=>T)=>withSqliteReadTransaction(db,()=>withBattedVenueLegalReadSnapshot(db,body));
  const admitted=read(admissionDb,()=>{
   const owned=timing.span('readback',()=>{const owned=readPhysicalClosureProposal(admissionDb,ids.closureSourceId);assert(owned&&owned.row.status==='COMPLETED','recovery requires an actual completed owner');assertRecoveryQueueBinding({sourceId:owned.source.sourceId,sourceHash:hash(owned.source),proposalHash:hash(owned.proposal)},metadata.queue.ownerReceipts.closure);assertPhysicalClosureStages(admissionDb,owned.proposal,true);const workload=readPhysicalClosureWorkload(admissionDb,owned.proposal);assert(workload);const result={sourceId:owned.source.sourceId,gameId:owned.row.game_id,playId:owned.row.play_id,official:owned.proposal.expectedOfficial,scoring:owned.proposal.expectedScoring,workload};same(result,metadata.original,'original completion return and real owner differ');same(JSON.parse(owned.row.result_json!),result,'completed result mirror differs');return{...owned,result};});
   const terminal=timing.span('prefix',()=>foulTerminalPostPlayCompletionEvidenceFromSqlite(admissionDb).read(ids.terminalSourceId));assert(terminal&&terminal.status==='POST_PLAY_COMPLETED_CONTINUING');const t=terminal.result.completion;assert(t.version==='actual_foul_terminal_post_play_completion_v1');
   const originalActor=owned.proposal.physicalPitch.frame.batterActor;assert(originalActor);const actions=admissionDb.prepare('SELECT * FROM physical_pitch_progress_actions WHERE game_id=? AND play_id=? ORDER BY progress_revision').all('game-1',8);same(actions.map(hash),owned.proposal.originalPitchRows.actions,'admitted physical row seal differs');const pitches=actions.map(row=>JSON.parse(String(row.snapshot_json)));same(pitches.map(p=>p.source.sourceId),ids.takeIds,'admitted physical Source identities differ');
   const originalOwners={terminal:{sourceId:ids.terminalSourceId,completionId:t.completionId,snapshotHash:t.snapshotHash,applicationId:terminal.proposal.source.applicationId,durableRevision:1},originalActor:{sourceId:originalActor.source.sourceId,snapshotHash:hash(originalActor)},physical:{playId:8,sourceIds:ids.takeIds,sourceHashes:pitches.map(p=>hash(p.source)),snapshotHashes:pitches.map(hash),status:'strikeout'}};
   for(const key of ['terminal','originalActor','physical']as const)same(originalOwners[key],metadata.queue.ownerReceipts[key],'recovery original owner lineage differs');
   same(readActualRoleWorkloadState(admissionDb,'career-a','p2'),owned.result.workload.after,'recovery current workload differs');assert(!admissionDb.prepare('SELECT 1 FROM physical_plate_appearance_actors WHERE source_id=?').get(ids.nextActorSourceId),'next actor already exists');
   const owners={...originalOwners,closure:{sourceId:owned.source.sourceId,status:'COMPLETED',sourceHash:hash(owned.source),proposalHash:hash(owned.proposal)},official:{applicationId:ids.applicationId,receiptHash:hash(owned.result.official.receipt),durableRevision:2,playId:9,outs:2},scoring:{scoringApplicationId:ids.scoringApplicationId,rowHash:hash(admissionDb.prepare('SELECT * FROM official_scoring_applications WHERE scoring_application_id=?').get(ids.scoringApplicationId))},workload:{sourceEventId:owned.result.workload.activity.sourceEventId,beforeRevision:owned.result.workload.before.revision,afterRevision:owned.result.workload.after.revision,activityHash:hash(owned.result.workload.activity),afterHash:hash(owned.result.workload.after)}};
   return{owned,owners};
  });
  same(rawCensus(admissionDb),before,'completed admission wrote rows');same(schemaCensus(admissionDb),schema,'completed admission changed schema');
  assertContinuationRows(metadata.queueCensus.rows,before,'closure_completed');same(metadata.queueCensus.schema,schema,'recovery changed Q1 storage');
  timing.span('close',()=>{closeAll();closed(admissionPath);syncFile(admissionPath);syncDir(admissionDirectory);});
  const admissionReceipt=save(join(admissionDirectory,'receipt.json'),{version:'terminal_completed_endpoint_admission_v1',sourceTree:input.sourceTree,originalFailedTuple:input.tuple,originalFailedAttemptCredit:0,artifact:{path:admissionPath,sha256:fileHash(admissionPath)},completionResultSha256:hash(admitted.owned.result),ownerReceipts:admitted.owners,allHandlesClosed:true,originalRowsPreserved:true});
  const finalDirectory=join(input.destinationDirectory,'closed');mkdirSync(finalDirectory,{mode:0o700});const finalPath=join(finalDirectory,'game.sqlite');copyFileSync(admissionPath,finalPath,constants.COPYFILE_EXCL);assert.equal(fileHash(finalPath),fileHash(admissionPath));
  const open=()=>{
   const db=track(new DatabaseSync(finalPath)),p=admitted.owned.proposal,f=p.physicalPitch.frame,binding=f.bindings[0],game=admitted.owned.source.game;
   const links=track(openSqlitePlayerPersonLinkStore(finalPath)),official=track(new SqliteOfficialStateStore(finalPath)),participation=track(new SqliteOfficialParticipationStore(finalPath,{readGame:id=>id===f.gameId?{careerId:binding.careerId,competitionEditionId:binding.competitionEditionId,gameDay:binding.gameDay,homeClubId:game.homeClubId,awayClubId:game.awayClubId,fixtureEventId:binding.fixtureEventId}:null,readRoster:()=>null,readPersonLink:(playerId,sourceId)=>{const link=links.readLink(sourceId);return link?.playerId===playerId?{sourceId,personId:link.personId}:null;}}));
   const initialWorlds=track(openSqliteOfficialInitialWorldStore(finalPath,{matches:official,participation})),workload=track(workloadOwner.openSqlitePlayerWorkloadRecoveryStore(finalPath,links)),timing=track(openSqlitePlayerPitchTimingStore(finalPath,links)),release=track(openSqlitePlayerReleaseGeometryStore(finalPath,links)),policies=track(openSqlitePitchFatiguePolicyStore(finalPath));
   const pitches=track(openSqlitePhysicalPitchProgressStore(finalPath,{matches:official,initialWorlds,participation,runtime:{workload,timing,release,policies,effortPolicies:{readAcceptedPolicy:id=>id===f.effortPolicy.sourceId?f.effortPolicy:null}}}));const closure=track(openSqlitePhysicalPlayClosureStore(finalPath,{physicalPitches:pitches,initialWorlds,participation,personLinks:links}));same(rawCensus(db),before,'recovery owner opening wrote rows');same(schemaCensus(db),schema,'recovery owner opening changed schema');return{db,closure};
  };
  for(const label of ['retry','reopen']as const){const x=open();timing.span(label,()=>{const result=x.closure.resume(ids.closureSourceId);observer.returned('completion',[ids.closureSourceId],result);same(result,admitted.owned.result,'recovery real completed retry differs');read(x.db,()=>{same(rawCensus(x.db),before,'recovery retry wrote rows');same(schemaCensus(x.db),schema,'recovery retry changed schema');});});timing.span('close',()=>{closeAll();closed(finalPath);syncFile(finalPath);syncDir(finalDirectory);});}
  metadata.verifyTuple();pin(input.tuple);pin(input.inspection);pin(input.queueReceipt);pin(input.queueQualification);pin(input.recipe);pin(metadata.queue.output);closed(metadata.queue.output.path);pin({path:admissionPath,sha256:readPin(admissionReceipt).artifact.sha256});
  const trace=observer.close(),spans=timing.close();const continuation=recoveredContinuationReceipt({sourceTree:input.sourceTree,recipe:input.recipe,queue:metadata.queue,admission:{artifact:{path:admissionPath,sha256:fileHash(admissionPath)},receipt:admissionReceipt,closed:true},output:{path:finalPath,sha256:fileHash(finalPath)},owners:admitted.owners});const continuationPath=join(input.destinationDirectory,'continuation-receipt.json'),continuationPin=save(continuationPath,continuation);
  const recovery={version:'terminal_completed_endpoint_recovery_receipt_v1',sourceTree:input.sourceTree,originalFailedTuple:input.tuple,originalFailedAttemptCredit:0,aggregateP1Credit:0,admission:admissionReceipt,continuation:continuationPin,output:continuation.output,trace,spans,actualCompletionResultSha256:hash(admitted.owned.result),effectOwnerCalls:0,completedResumeReturns:2,allHandlesClosed:true,reopened:true,originalRowsPreserved:true};save(input.receiptPath,recovery);return recovery;
 }catch(error){failed=true;primary=error;throw error;}finally{const errors:unknown[]=[];try{closeAll();}catch(error){errors.push(error);}while(restores.length)try{restores.pop()!();}catch(error){errors.push(error);}for(const trace of [observer,timing])try{trace.close();}catch(error){errors.push(error);}if(errors.length)throw new AggregateError(failed?[primary,...errors]:errors,'completed recovery cleanup failed',{cause:failed?primary:errors[0]});}
};
