import {expect,it} from 'vitest';
import * as exported from './TerminalCompletedEndpointRecovery.test-support';
const api=()=>{const m=exported as any;expect(typeof m.captureCompletedRecoveryInput,'COMPLETED_RECOVERY_API_MISSING').toBe('function');return m;};
const pin=(path='/private/control.json')=>({path,sha256:'a'.repeat(64)});
const input=()=>({version:'terminal_completed_endpoint_recovery_v1',nativeReleased:false,sourceTree:'b'.repeat(40),tuple:pin(),inspection:pin(),queueReceipt:pin(),queueQualification:pin(),recipe:pin(),destinationDirectory:'/private/new',receiptPath:'/private/new/receipt.json'});
// Structural metadata/fake-owner contracts only. No original proof is replaced.
it('CR-S01 captures inert reviewed controls and refuses unreleased recovery before IO',()=>{const m=api(),v=input();expect(m.captureCompletedRecoveryInput(v)).toEqual(v);expect(()=>m.runCompletedEndpointRecovery(v)).toThrow('not been reviewed and released');let reads=0;Object.defineProperty(v,'tuple',{enumerable:true,get(){reads++;return pin();}});expect(()=>m.captureCompletedRecoveryInput(v)).toThrow();expect(reads).toBe(0);});
it('CR-S02 requires the full retained main WAL and SHM tuple from the failed attempt',()=>{const m=api();const base='/private/failed/game.sqlite';const files=['','-wal','-shm'].map((suffix,index)=>({path:base+suffix,exists:true,bytes:index===1?8272:32768,sha256:'a'.repeat(64),device:1,inode:index+1,mtimeNs:1,ctimeNs:1}));files.push({path:base+'-journal',exists:false}as any);const tuple={schema:'capped_ordinary_completion_tuple_v1',originalAggregateCredit:0,terminal:pin(),config:pin(),input:pin(),events:pin(),returnedValues:Array.from({length:6},()=>pin()),files};expect(()=>m.validateCompletedRecoveryTuple(tuple)).not.toThrow();expect(()=>m.validateCompletedRecoveryTuple({...tuple,files:files.filter(r=>!r.path.endsWith('-wal'))})).toThrow();expect(()=>m.validateCompletedRecoveryTuple({...tuple,files:files.map(r=>r.path.endsWith('-wal')?{...r,bytes:0}:r)})).toThrow();});
it('CR-S03 forbids effect-owner calls before invocation while preserving real reads and close binding',()=>{const m=api();let writes=0,closed=0;const value={},owner=Object.freeze({apply(){writes++;return value;},read(this:unknown){expect(this).toBe(owner);return value;},close(this:unknown){expect(this).toBe(owner);closed++;}});const guarded=m.forbidRecoveryOwnerCalls(owner,['apply']);expect(()=>guarded.apply()).toThrow('recovery forbids effect owner');expect(writes).toBe(0);expect(guarded.read()).toBe(value);guarded.close();expect(closed).toBe(1);});
it('CR-S04 binds the continuation view to its actual closed Native admission receipt',()=>{const m=api(),origin={kind:'qualified_single_pitch_chain',qualifiedInput:pin(),physicalReceipt:pin(),aggregateP1Credit:0},args={sourceTree:'b'.repeat(40),recipe:pin(),queue:{version:'terminal_continuation_stage_v2',stage:'closure_queued',sourceTree:'b'.repeat(40),recipeHash:'a'.repeat(64),splitPhysicalOrigin:origin},admission:{artifact:pin('/private/admission.sqlite'),receipt:pin('/private/admission.json'),closed:true},output:pin('/private/recovered.sqlite'),owners:{closure:{status:'COMPLETED'}}};const r=m.recoveredContinuationReceipt(args);expect(r.version).toBe('terminal_continuation_stage_v2');expect(r.stage).toBe('closure_completed');expect(r.input).toEqual(args.admission.artifact);expect(r.predecessorReceiptHash).toBe(args.admission.receipt.sha256);expect(r.splitPhysicalOrigin).toEqual(origin);expect(r.twoPriorCompletionLineage).toBe(false);expect(()=>m.recoveredContinuationReceipt({...args,admission:{...args.admission,closed:false}})).toThrow();});
it('CR-S05 preserves the exact queued Source and proposal through completed recovery',()=>{const m=api();expect(typeof m.assertRecoveryQueueBinding,'RECOVERED_QUEUE_BINDING_MISSING').toBe('function');const actual={sourceId:'terminal-continuation-k-close',sourceHash:'a'.repeat(64),proposalHash:'b'.repeat(64)},queue={...actual,status:'PENDING'};expect(()=>m.assertRecoveryQueueBinding(actual,queue)).not.toThrow();expect(()=>m.assertRecoveryQueueBinding({...actual,sourceHash:'c'.repeat(64)},queue)).toThrow();expect(()=>m.assertRecoveryQueueBinding({...actual,proposalHash:'c'.repeat(64)},queue)).toThrow();});
